// All 254 Texas counties (statewide cadastral: boundaries + abstracts +
// survey names live in PostGIS and stream as vector tiles). Generated from
// tx-counties.geojson — fips is the 3-digit RRC/API county code.
export interface CountyDef { key: string; name: string; fips: string }

export const COUNTIES: CountyDef[] = [
  { key: "anderson", name: "Anderson", fips: "001" },
  { key: "andrews", name: "Andrews", fips: "003" },
  { key: "angelina", name: "Angelina", fips: "005" },
  { key: "aransas", name: "Aransas", fips: "007" },
  { key: "archer", name: "Archer", fips: "009" },
  { key: "armstrong", name: "Armstrong", fips: "011" },
  { key: "atascosa", name: "Atascosa", fips: "013" },
  { key: "austin", name: "Austin", fips: "015" },
  { key: "bailey", name: "Bailey", fips: "017" },
  { key: "bandera", name: "Bandera", fips: "019" },
  { key: "bastrop", name: "Bastrop", fips: "021" },
  { key: "baylor", name: "Baylor", fips: "023" },
  { key: "bee", name: "Bee", fips: "025" },
  { key: "bell", name: "Bell", fips: "027" },
  { key: "bexar", name: "Bexar", fips: "029" },
  { key: "blanco", name: "Blanco", fips: "031" },
  { key: "borden", name: "Borden", fips: "033" },
  { key: "bosque", name: "Bosque", fips: "035" },
  { key: "bowie", name: "Bowie", fips: "037" },
  { key: "brazoria", name: "Brazoria", fips: "039" },
  { key: "brazos", name: "Brazos", fips: "041" },
  { key: "brewster", name: "Brewster", fips: "043" },
  { key: "briscoe", name: "Briscoe", fips: "045" },
  { key: "brooks", name: "Brooks", fips: "047" },
  { key: "brown", name: "Brown", fips: "049" },
  { key: "burleson", name: "Burleson", fips: "051" },
  { key: "burnet", name: "Burnet", fips: "053" },
  { key: "caldwell", name: "Caldwell", fips: "055" },
  { key: "calhoun", name: "Calhoun", fips: "057" },
  { key: "callahan", name: "Callahan", fips: "059" },
  { key: "cameron", name: "Cameron", fips: "061" },
  { key: "camp", name: "Camp", fips: "063" },
  { key: "carson", name: "Carson", fips: "065" },
  { key: "cass", name: "Cass", fips: "067" },
  { key: "castro", name: "Castro", fips: "069" },
  { key: "chambers", name: "Chambers", fips: "071" },
  { key: "cherokee", name: "Cherokee", fips: "073" },
  { key: "childress", name: "Childress", fips: "075" },
  { key: "clay", name: "Clay", fips: "077" },
  { key: "cochran", name: "Cochran", fips: "079" },
  { key: "coke", name: "Coke", fips: "081" },
  { key: "coleman", name: "Coleman", fips: "083" },
  { key: "collin", name: "Collin", fips: "085" },
  { key: "collingsworth", name: "Collingsworth", fips: "087" },
  { key: "colorado", name: "Colorado", fips: "089" },
  { key: "comal", name: "Comal", fips: "091" },
  { key: "comanche", name: "Comanche", fips: "093" },
  { key: "concho", name: "Concho", fips: "095" },
  { key: "cooke", name: "Cooke", fips: "097" },
  { key: "coryell", name: "Coryell", fips: "099" },
  { key: "cottle", name: "Cottle", fips: "101" },
  { key: "crane", name: "Crane", fips: "103" },
  { key: "crockett", name: "Crockett", fips: "105" },
  { key: "crosby", name: "Crosby", fips: "107" },
  { key: "culberson", name: "Culberson", fips: "109" },
  { key: "dallam", name: "Dallam", fips: "111" },
  { key: "dallas", name: "Dallas", fips: "113" },
  { key: "dawson", name: "Dawson", fips: "115" },
  { key: "dewitt", name: "DeWitt", fips: "123" },
  { key: "deafsmith", name: "Deaf Smith", fips: "117" },
  { key: "delta", name: "Delta", fips: "119" },
  { key: "denton", name: "Denton", fips: "121" },
  { key: "dickens", name: "Dickens", fips: "125" },
  { key: "dimmit", name: "Dimmit", fips: "127" },
  { key: "donley", name: "Donley", fips: "129" },
  { key: "duval", name: "Duval", fips: "131" },
  { key: "eastland", name: "Eastland", fips: "133" },
  { key: "ector", name: "Ector", fips: "135" },
  { key: "edwards", name: "Edwards", fips: "137" },
  { key: "elpaso", name: "El Paso", fips: "141" },
  { key: "ellis", name: "Ellis", fips: "139" },
  { key: "erath", name: "Erath", fips: "143" },
  { key: "falls", name: "Falls", fips: "145" },
  { key: "fannin", name: "Fannin", fips: "147" },
  { key: "fayette", name: "Fayette", fips: "149" },
  { key: "fisher", name: "Fisher", fips: "151" },
  { key: "floyd", name: "Floyd", fips: "153" },
  { key: "foard", name: "Foard", fips: "155" },
  { key: "fortbend", name: "Fort Bend", fips: "157" },
  { key: "franklin", name: "Franklin", fips: "159" },
  { key: "freestone", name: "Freestone", fips: "161" },
  { key: "frio", name: "Frio", fips: "163" },
  { key: "gaines", name: "Gaines", fips: "165" },
  { key: "galveston", name: "Galveston", fips: "167" },
  { key: "garza", name: "Garza", fips: "169" },
  { key: "gillespie", name: "Gillespie", fips: "171" },
  { key: "glasscock", name: "Glasscock", fips: "173" },
  { key: "goliad", name: "Goliad", fips: "175" },
  { key: "gonzales", name: "Gonzales", fips: "177" },
  { key: "gray", name: "Gray", fips: "179" },
  { key: "grayson", name: "Grayson", fips: "181" },
  { key: "gregg", name: "Gregg", fips: "183" },
  { key: "grimes", name: "Grimes", fips: "185" },
  { key: "guadalupe", name: "Guadalupe", fips: "187" },
  { key: "hale", name: "Hale", fips: "189" },
  { key: "hall", name: "Hall", fips: "191" },
  { key: "hamilton", name: "Hamilton", fips: "193" },
  { key: "hansford", name: "Hansford", fips: "195" },
  { key: "hardeman", name: "Hardeman", fips: "197" },
  { key: "hardin", name: "Hardin", fips: "199" },
  { key: "harris", name: "Harris", fips: "201" },
  { key: "harrison", name: "Harrison", fips: "203" },
  { key: "hartley", name: "Hartley", fips: "205" },
  { key: "haskell", name: "Haskell", fips: "207" },
  { key: "hays", name: "Hays", fips: "209" },
  { key: "hemphill", name: "Hemphill", fips: "211" },
  { key: "henderson", name: "Henderson", fips: "213" },
  { key: "hidalgo", name: "Hidalgo", fips: "215" },
  { key: "hill", name: "Hill", fips: "217" },
  { key: "hockley", name: "Hockley", fips: "219" },
  { key: "hood", name: "Hood", fips: "221" },
  { key: "hopkins", name: "Hopkins", fips: "223" },
  { key: "houston", name: "Houston", fips: "225" },
  { key: "howard", name: "Howard", fips: "227" },
  { key: "hudspeth", name: "Hudspeth", fips: "229" },
  { key: "hunt", name: "Hunt", fips: "231" },
  { key: "hutchinson", name: "Hutchinson", fips: "233" },
  { key: "irion", name: "Irion", fips: "235" },
  { key: "jack", name: "Jack", fips: "237" },
  { key: "jackson", name: "Jackson", fips: "239" },
  { key: "jasper", name: "Jasper", fips: "241" },
  { key: "jeffdavis", name: "Jeff Davis", fips: "243" },
  { key: "jefferson", name: "Jefferson", fips: "245" },
  { key: "jimhogg", name: "Jim Hogg", fips: "247" },
  { key: "jimwells", name: "Jim Wells", fips: "249" },
  { key: "johnson", name: "Johnson", fips: "251" },
  { key: "jones", name: "Jones", fips: "253" },
  { key: "karnes", name: "Karnes", fips: "255" },
  { key: "kaufman", name: "Kaufman", fips: "257" },
  { key: "kendall", name: "Kendall", fips: "259" },
  { key: "kenedy", name: "Kenedy", fips: "261" },
  { key: "kent", name: "Kent", fips: "263" },
  { key: "kerr", name: "Kerr", fips: "265" },
  { key: "kimble", name: "Kimble", fips: "267" },
  { key: "king", name: "King", fips: "269" },
  { key: "kinney", name: "Kinney", fips: "271" },
  { key: "kleberg", name: "Kleberg", fips: "273" },
  { key: "knox", name: "Knox", fips: "275" },
  { key: "lasalle", name: "La Salle", fips: "283" },
  { key: "lamar", name: "Lamar", fips: "277" },
  { key: "lamb", name: "Lamb", fips: "279" },
  { key: "lampasas", name: "Lampasas", fips: "281" },
  { key: "lavaca", name: "Lavaca", fips: "285" },
  { key: "lee", name: "Lee", fips: "287" },
  { key: "leon", name: "Leon", fips: "289" },
  { key: "liberty", name: "Liberty", fips: "291" },
  { key: "limestone", name: "Limestone", fips: "293" },
  { key: "lipscomb", name: "Lipscomb", fips: "295" },
  { key: "liveoak", name: "Live Oak", fips: "297" },
  { key: "llano", name: "Llano", fips: "299" },
  { key: "loving", name: "Loving", fips: "301" },
  { key: "lubbock", name: "Lubbock", fips: "303" },
  { key: "lynn", name: "Lynn", fips: "305" },
  { key: "madison", name: "Madison", fips: "313" },
  { key: "marion", name: "Marion", fips: "315" },
  { key: "martin", name: "Martin", fips: "317" },
  { key: "mason", name: "Mason", fips: "319" },
  { key: "matagorda", name: "Matagorda", fips: "321" },
  { key: "maverick", name: "Maverick", fips: "323" },
  { key: "mcculloch", name: "McCulloch", fips: "307" },
  { key: "mclennan", name: "McLennan", fips: "309" },
  { key: "mcmullen", name: "McMullen", fips: "311" },
  { key: "medina", name: "Medina", fips: "325" },
  { key: "menard", name: "Menard", fips: "327" },
  { key: "midland", name: "Midland", fips: "329" },
  { key: "milam", name: "Milam", fips: "331" },
  { key: "mills", name: "Mills", fips: "333" },
  { key: "mitchell", name: "Mitchell", fips: "335" },
  { key: "montague", name: "Montague", fips: "337" },
  { key: "montgomery", name: "Montgomery", fips: "339" },
  { key: "moore", name: "Moore", fips: "341" },
  { key: "morris", name: "Morris", fips: "343" },
  { key: "motley", name: "Motley", fips: "345" },
  { key: "nacogdoches", name: "Nacogdoches", fips: "347" },
  { key: "navarro", name: "Navarro", fips: "349" },
  { key: "newton", name: "Newton", fips: "351" },
  { key: "nolan", name: "Nolan", fips: "353" },
  { key: "nueces", name: "Nueces", fips: "355" },
  { key: "ochiltree", name: "Ochiltree", fips: "357" },
  { key: "oldham", name: "Oldham", fips: "359" },
  { key: "orange", name: "Orange", fips: "361" },
  { key: "palopinto", name: "Palo Pinto", fips: "363" },
  { key: "panola", name: "Panola", fips: "365" },
  { key: "parker", name: "Parker", fips: "367" },
  { key: "parmer", name: "Parmer", fips: "369" },
  { key: "pecos", name: "Pecos", fips: "371" },
  { key: "polk", name: "Polk", fips: "373" },
  { key: "potter", name: "Potter", fips: "375" },
  { key: "presidio", name: "Presidio", fips: "377" },
  { key: "rains", name: "Rains", fips: "379" },
  { key: "randall", name: "Randall", fips: "381" },
  { key: "reagan", name: "Reagan", fips: "383" },
  { key: "real", name: "Real", fips: "385" },
  { key: "redriver", name: "Red River", fips: "387" },
  { key: "reeves", name: "Reeves", fips: "389" },
  { key: "refugio", name: "Refugio", fips: "391" },
  { key: "roberts", name: "Roberts", fips: "393" },
  { key: "robertson", name: "Robertson", fips: "395" },
  { key: "rockwall", name: "Rockwall", fips: "397" },
  { key: "runnels", name: "Runnels", fips: "399" },
  { key: "rusk", name: "Rusk", fips: "401" },
  { key: "sabine", name: "Sabine", fips: "403" },
  { key: "sanaugustine", name: "San Augustine", fips: "405" },
  { key: "sanjacinto", name: "San Jacinto", fips: "407" },
  { key: "sanpatricio", name: "San Patricio", fips: "409" },
  { key: "sansaba", name: "San Saba", fips: "411" },
  { key: "schleicher", name: "Schleicher", fips: "413" },
  { key: "scurry", name: "Scurry", fips: "415" },
  { key: "shackelford", name: "Shackelford", fips: "417" },
  { key: "shelby", name: "Shelby", fips: "419" },
  { key: "sherman", name: "Sherman", fips: "421" },
  { key: "smith", name: "Smith", fips: "423" },
  { key: "somervell", name: "Somervell", fips: "425" },
  { key: "starr", name: "Starr", fips: "427" },
  { key: "stephens", name: "Stephens", fips: "429" },
  { key: "sterling", name: "Sterling", fips: "431" },
  { key: "stonewall", name: "Stonewall", fips: "433" },
  { key: "sutton", name: "Sutton", fips: "435" },
  { key: "swisher", name: "Swisher", fips: "437" },
  { key: "tarrant", name: "Tarrant", fips: "439" },
  { key: "taylor", name: "Taylor", fips: "441" },
  { key: "terrell", name: "Terrell", fips: "443" },
  { key: "terry", name: "Terry", fips: "445" },
  { key: "throckmorton", name: "Throckmorton", fips: "447" },
  { key: "titus", name: "Titus", fips: "449" },
  { key: "tomgreen", name: "Tom Green", fips: "451" },
  { key: "travis", name: "Travis", fips: "453" },
  { key: "trinity", name: "Trinity", fips: "455" },
  { key: "tyler", name: "Tyler", fips: "457" },
  { key: "upshur", name: "Upshur", fips: "459" },
  { key: "upton", name: "Upton", fips: "461" },
  { key: "uvalde", name: "Uvalde", fips: "463" },
  { key: "valverde", name: "Val Verde", fips: "465" },
  { key: "vanzandt", name: "Van Zandt", fips: "467" },
  { key: "victoria", name: "Victoria", fips: "469" },
  { key: "walker", name: "Walker", fips: "471" },
  { key: "waller", name: "Waller", fips: "473" },
  { key: "ward", name: "Ward", fips: "475" },
  { key: "washington", name: "Washington", fips: "477" },
  { key: "webb", name: "Webb", fips: "479" },
  { key: "wharton", name: "Wharton", fips: "481" },
  { key: "wheeler", name: "Wheeler", fips: "483" },
  { key: "wichita", name: "Wichita", fips: "485" },
  { key: "wilbarger", name: "Wilbarger", fips: "487" },
  { key: "willacy", name: "Willacy", fips: "489" },
  { key: "williamson", name: "Williamson", fips: "491" },
  { key: "wilson", name: "Wilson", fips: "493" },
  { key: "winkler", name: "Winkler", fips: "495" },
  { key: "wise", name: "Wise", fips: "497" },
  { key: "wood", name: "Wood", fips: "499" },
  { key: "yoakum", name: "Yoakum", fips: "501" },
  { key: "young", name: "Young", fips: "503" },
  { key: "zapata", name: "Zapata", fips: "505" },
  { key: "zavala", name: "Zavala", fips: "507" },
];

/** County keys with well/wellbore data imported into rrc.wells (phase B2). */
export const COUNTIES_WITH_WELLS = [
  "leon", "freestone", "anderson", "angelina", "cherokee", "houston",
  "limestone", "madison", "panola", "robertson", "sanaugustine", "shelby",
];

/** County keys with a {key}-production.json monthly-production asset (heat map; phase B5 replaces). */
export const COUNTIES_WITH_PRODUCTION = ["leon", "freestone"];
