import { Router } from "express";
import rateLimit from "express-rate-limit";
import { z } from "zod";
import { prisma, withDbRetry } from "../db.js";
import { asyncHandler } from "../middleware/errors.js";
import { requireAuth, requireOrg, requirePermission, orgId, type AuthedRequest } from "../middleware/auth.js";
import { escapeLike, rankRefEntries, MIN_SEARCH_CHARS, type RefEntry } from "../domain/search.js";
import { abstractNumber, countyLabel, countyStateLabel, isSectionLabel, rankAbstracts, sectionLabel, surveyLabel } from "../domain/abstractLabel.js";
import { countyKey, countyNoun, countyScopePredicate, countySearchTerm, GIS_STATES, louisianaParishNames, parsePlssQuery, texasCountyNames } from "../domain/gisRegion.js";
import { isLaFid, laParishLabel } from "../domain/sonrisWells.js";
import { sonrisWellsAvailable } from "../services/sonrisWells.js";
import { identifierDigits, LA_WELL_SQL, laWellDetail } from "../services/sonrisQueries.js";

/**
 * GIS Phase A (see docs/architecture/0003-gis-scale-architecture.md).
 *
 * Cadastral data lives in PostGIS (`gis` schema on the existing Neon DB) and is
 * delivered to MapLibre as vector tiles generated by ST_AsMVT. Search and
 * filter-option lists are trigram-backed queries — the client no longer needs
 * any abstract data downloaded to search or filter it.
 *
 * Tiles are mounted un-authed: MapLibre tile requests don't carry the
 * Authorization header, and the payload is public-record survey geometry
 * (same data UT BEG serves publicly). Everything org- or deal-related stays
 * on the authed routers.
 *
 * Coverage is multi-state: gis.counties / gis.abstracts carry Texas counties +
 * abstracts and Louisiana parishes + PLSS sections (services/gisRegions.ts
 * loads the latter at boot), told apart by their `state` column. County names
 * repeat across states (Sabine, Red River), so every county-scoped query here
 * goes through domain/gisRegion's state-qualified keys.
 *
 * Wells are multi-state too: Texas RRC wells (rrc.*) and Louisiana SONRIS
 * wells (sonris.*, services/sonrisWells.ts) share the `wells` / `wellbores`
 * tile layers, the status/type vocabulary, search and filter options.
 * Louisiana feature ids sit in their own block (domain/sonrisWells: 2e9 +
 * serial), so a fid alone says which table a well lives in. Every sonris
 * query is gated on sonrisWellsAvailable() — a database without that schema
 * serves Texas exactly as before.
 */

const TILE_EXTENT = 4096;
const TILE_BUFFER = 64;
/** County boundaries (full-resolution TIGER) serve at every zoom; denser
 * layers gate in as their content becomes legible. Statewide, a z7 tile would
 * carry 15–20k abstracts (~2 MB) — too slow to generate and pointless to
 * render — so abstract detail starts at z8. */
const TILE_MIN_ZOOM = 0;
const TILE_MAX_ZOOM = 22;
const ABSTRACTS_MIN_ZOOM = 8;
/** Well points/laterals only render usefully once zoomed in; gating them here
 * keeps low-zoom tiles slim (a dense county can hold 10k+ wells). */
const WELLS_MIN_ZOOM = 9;
const BORES_MIN_ZOOM = 10;

// Tiny insertion-order LRU. Cadastral data changes only on re-import, so a
// process-lifetime cache is safe; Railway redeploys (and imports precede
// deploys) naturally flush it.
const tileCache = new Map<string, Buffer>();
const TILE_CACHE_MAX = 800;
function cachePut(key: string, buf: Buffer): void {
  if (tileCache.size >= TILE_CACHE_MAX) {
    const oldest = tileCache.keys().next().value;
    if (oldest !== undefined) tileCache.delete(oldest);
  }
  tileCache.set(key, buf);
}
/** Get + refresh recency (true LRU): hot tiles survive pans across the state. */
function cacheGet(key: string): Buffer | undefined {
  const hit = tileCache.get(key);
  if (hit) { tileCache.delete(key); tileCache.set(key, hit); }
  return hit;
}

/**
 * The tile query. Bbox filter runs against the 4326 GIST indexes; only
 * intersecting rows get transformed/clipped. ST_AsMVTGeom quantizes to the
 * tile grid, so payload size tracks the viewport, not the tables. An MVT is a
 * protobuf whose layers are independent messages, so concatenating per-layer
 * ST_AsMVT buffers yields one multi-layer tile. Wellbore rows join their
 * surface well's attributes so the client can apply identical filter
 * expressions to both layers.
 *
 * With `sonris` on, Louisiana wells/bores join the SAME `wells` / `wellbores`
 * layers (UNION ALL, identical columns): status/type/symbol are already in the
 * Texas vocabulary, `abstract`/`survey` carry the PLSS section ("Sec 12") and
 * township ("T12N R10W"), and `state` tells the two apart ('TX' | 'LA').
 * $1/$2/$3 = z/x/y.
 */
export function buildTileSql(sonris: boolean): string {
  const mvt = (g: string) => `ST_AsMVTGeom(ST_Transform(${g}, 3857), w.env, ${TILE_EXTENT}, ${TILE_BUFFER}, true)`;
  const laWells = sonris ? `
         UNION ALL
         SELECT ${mvt("lw.geom")} AS geom,
                lw.fid, NULL::text AS api8, lw.well_no AS "wellNo", lw.symbol, lw.type, lw.status,
                lw.parish AS county, lw.operator, CASE WHEN lw.section > 0 THEN 'Sec ' || lw.section END AS abstract,
                lw.township AS survey, 'LA'::text AS state
           FROM sonris.wells lw, wanted w WHERE lw.geom && w.box` : "";
  const laBores = sonris ? `
         UNION ALL
         SELECT ${mvt("lb.geom")} AS geom,
                lb.fid, lb.surface_fid AS "surfaceId", lb.wellbore_type AS "wellboreType",
                lsw.type, lsw.status, lsw.parish AS county, lsw.operator,
                CASE WHEN lsw.section > 0 THEN 'Sec ' || lsw.section END AS abstract, lsw.township AS survey, 'LA'::text AS state
           FROM sonris.wellbores lb
           LEFT JOIN sonris.wells lsw ON lsw.fid = lb.surface_fid, wanted w
          WHERE lb.geom && w.box` : "";
  return `WITH bounds AS (SELECT ST_TileEnvelope($1::int, $2::int, $3::int) AS env),
       wanted AS (SELECT ST_Transform(ST_Expand(env, 4000), 4326) AS box, env FROM bounds),
       cty_mvt AS (
         SELECT ${mvt("c.geom")} AS geom,
                c.fips, c.name, c.state
           FROM gis.counties c, wanted w WHERE c.geom && w.box
       ),
       abs_mvt AS (
         SELECT ${mvt("a.geom")} AS geom,
                a.id, a.state, a.county, replace(a.abstract, '?', '') AS abstract, a.survey, a.area_m2 AS area
           FROM gis.abstracts a, wanted w WHERE a.geom && w.box
       ),
       well_mvt AS (
         SELECT ${mvt("wl.geom")} AS geom,
                wl.fid, wl.api8, wl.well_no AS "wellNo", wl.symbol, wl.type, wl.status,
                wl.county, wl.operator, replace(wl.abstract, '?', '') AS abstract, wl.survey, 'TX'::text AS state
           FROM rrc.wells wl, wanted w WHERE wl.geom && w.box${laWells}
       ),
       bore_mvt AS (
         SELECT ${mvt("b.geom")} AS geom,
                b.fid, b.surface_fid AS "surfaceId", b.wellbore_type AS "wellboreType",
                sw.type, sw.status, sw.county, sw.operator, replace(sw.abstract, '?', '') AS abstract, sw.survey, 'TX'::text AS state
           FROM rrc.wellbores b
           LEFT JOIN rrc.wells sw ON sw.fid = b.surface_fid, wanted w
          WHERE b.geom && w.box${laBores}
       ),
       dome_mvt AS (
         -- East Texas Basin salt dome outlines, digitized from BEG RI-140's
         -- per-dome structure-contour maps (basis = which contour was traced).
         SELECT ${mvt("sd.geom")} AS geom,
                sd.id, sd.name, sd.county, sd.crest_ft AS "crestFt", sd.basis
           FROM gis.salt_domes sd, wanted w WHERE sd.geom && w.box
       )
       SELECT coalesce((SELECT ST_AsMVT(cty_mvt, 'counties', ${TILE_EXTENT}, 'geom') FROM cty_mvt WHERE geom IS NOT NULL), ''::bytea)
           || coalesce((SELECT ST_AsMVT(dome_mvt, 'saltdomes', ${TILE_EXTENT}, 'geom') FROM dome_mvt WHERE geom IS NOT NULL), ''::bytea)
           || CASE WHEN $1::int >= ${ABSTRACTS_MIN_ZOOM} THEN coalesce((SELECT ST_AsMVT(abs_mvt, 'abstracts', ${TILE_EXTENT}, 'geom') FROM abs_mvt WHERE geom IS NOT NULL), ''::bytea) ELSE ''::bytea END
           || CASE WHEN $1::int >= ${WELLS_MIN_ZOOM} THEN coalesce((SELECT ST_AsMVT(well_mvt, 'wells', ${TILE_EXTENT}, 'geom') FROM well_mvt WHERE geom IS NOT NULL), ''::bytea) ELSE ''::bytea END
           || CASE WHEN $1::int >= ${BORES_MIN_ZOOM} THEN coalesce((SELECT ST_AsMVT(bore_mvt, 'wellbores', ${TILE_EXTENT}, 'geom') FROM bore_mvt WHERE geom IS NOT NULL), ''::bytea) ELSE ''::bytea END AS tile`;
}

export const gisTilesRouter = Router();

/**
 * The tile endpoint is intentionally unauthenticated (MapLibre can't attach an
 * Authorization header, and the underlying survey data is public record), so a
 * per-IP cap is the only backstop against someone walking the z/x/y space to
 * force uncached PostGIS tile generation in a loop. The ceiling is deliberately
 * generous: a real user panning and zooming a statewide map pulls tiles in
 * bursts of hundreds, and most of those are served from the LRU without
 * touching Postgres. Per-process (not DB-backed) on purpose — this guards CPU
 * on the instance actually doing the work, and must not add a write per tile.
 */
const tileLimiter = rateLimit({
  windowMs: 5 * 60 * 1000,
  max: 2000,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many tile requests — please slow down." },
});

gisTilesRouter.get(
  "/:z/:x/:y.pbf",
  tileLimiter,
  asyncHandler(async (req, res) => {
    const z = Number(req.params.z), x = Number(req.params.x), y = Number(req.params.y);
    if (!Number.isInteger(z) || !Number.isInteger(x) || !Number.isInteger(y) || z < 0 || z > TILE_MAX_ZOOM || x < 0 || y < 0 || x >= 2 ** z || y >= 2 ** z) {
      return res.status(400).json({ error: "invalid tile coordinates" });
    }
    res.setHeader("Content-Type", "application/x-protobuf");
    res.setHeader("Cache-Control", "public, max-age=3600");
    if (z < TILE_MIN_ZOOM) return res.status(204).end();

    const key = `${z}/${x}/${y}`;
    const hit = cacheGet(key);
    if (hit) return res.send(hit);

    // Wrapped in withDbRetry: this route is un-authed and high-frequency, so it
    // is the one most likely to catch a transient Neon reconnect blip (P1001).
    // The retry is happy-path-transparent — the query runs once when the DB is
    // reachable, and only re-runs on a connection error.
    const rows = await withDbRetry(() =>
      prisma.$queryRawUnsafe<{ tile: Buffer | null }[]>(buildTileSql(sonrisWellsAvailable()), z, x, y));
    const tile = rows[0]?.tile;
    if (!tile || tile.length === 0) return res.status(204).end();
    cachePut(key, tile);
    res.send(tile);
  }),
);

export const gisRouter = Router();
gisRouter.use(requireAuth, requireOrg, requirePermission("viewMap"));

// Same exposure the tile route above is capped for, one layer in: /suggest runs
// trigram matching across gis.abstracts and rrc.wells and aggregates operator
// and field extents, and /options and /extent scan on filter values — all of it
// behind a VIEW permission, so a read-only member could otherwise loop any of
// them and saturate the pool. Sized like the wells router: search fires per
// keystroke behind a debounce, so the ceiling has to clear real typing.
gisRouter.use(rateLimit({
  windowMs: 5 * 60 * 1000,
  max: 300,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: "Too many map requests. Wait a moment and try again." },
}));

// Three characters, not one — the same rule and the same reason as
// /api/wells/rrc-search: every predicate below is a leading-wildcard match, and
// a shorter term cannot probe the trigram indexes in
// scripts/ensureSearchIndexes.ts, so it seq-scans rrc.wells / gis.abstracts
// instead. The map search box enforces the same floor client-side.
const searchSchema = z.object({ q: z.string().trim().min(MIN_SEARCH_CHARS).max(120) });

// ---------------------------------------------------------------------------
// Reference index — precomputed operator / field / formation lists
//
// /suggest used to derive these per request: `GROUP BY operator` (and
// field_name, and `unnest(formations)`) across rrc.wells, three aggregations
// over the whole table on every keystroke. The formations one can never be
// indexed at all — `unnest` forces a full scan regardless of the term — so no
// amount of index work fixes it in place.
//
// They are aggregations over IMMUTABLE reference data: rrc.wells changes only
// on the monthly ingest. So compute them once and rank in memory (see
// domain/search), which is the same reasoning as the tile LRU above. Cost per
// request drops from three full-table aggregations to a filter over a few
// thousand cached rows.
//
// Single-flight: a cold cache under concurrent load must issue ONE load, not
// one per waiting request — a stampede is the very thing being prevented here.
// ---------------------------------------------------------------------------

interface WellReferenceIndex {
  operators: RefEntry[];
  fields: RefEntry[];
  formations: RefEntry[];
  /** Filter-option lists for the unscoped (no county selected) /options call. */
  types: string[];
  statuses: string[];
  wellCount: number;
  surveys: string[];
  abstracts: string[];
}

const EMPTY_REFERENCE: WellReferenceIndex = {
  operators: [], fields: [], formations: [], types: [], statuses: [], wellCount: 0, surveys: [], abstracts: [],
};

/** Reference data is re-imported monthly; re-read it a few times a day. */
const REFERENCE_TTL_MS = 6 * 60 * 60 * 1000;
/** A failed load (rrc schema absent in dev, transient blip) retries soon. */
const REFERENCE_ERROR_TTL_MS = 30 * 1000;

let referenceCache: { at: number; ttl: number; value: WellReferenceIndex } | null = null;
let referenceInFlight: Promise<WellReferenceIndex> | null = null;

async function loadReferenceIndex(): Promise<WellReferenceIndex> {
  // Column names are hard-coded literals, never request input.
  const agg = (col: string) => prisma.$queryRawUnsafe<{ name: string; n: number; ext: string | null }[]>(
    `SELECT ${col} AS name, count(*)::int AS n, ST_Extent(geom)::text AS ext
       FROM rrc.wells WHERE ${col} IS NOT NULL AND ${col} <> '' GROUP BY ${col}`,
  );
  const [operators, fields, formations, wellAgg, absAgg] = await Promise.all([
    agg("operator"),
    agg("field_name"),
    prisma.$queryRawUnsafe<{ name: string; n: number; ext: string | null }[]>(
      `SELECT f AS name, count(*)::int AS n, ST_Extent(geom)::text AS ext
         FROM rrc.wells, unnest(formations) AS f WHERE f IS NOT NULL AND f <> '' GROUP BY f`,
    ),
    prisma.$queryRawUnsafe<{ types: string[] | null; statuses: string[] | null; n: number }[]>(
      `SELECT array_agg(DISTINCT type) FILTER (WHERE type IS NOT NULL) AS types,
              array_agg(DISTINCT status) FILTER (WHERE status IS NOT NULL) AS statuses,
              count(*)::int AS n
         FROM rrc.wells`,
    ),
    prisma.$queryRawUnsafe<{ surveys: string[] | null; abstracts: string[] | null }[]>(
      `SELECT array_agg(DISTINCT survey) FILTER (WHERE survey IS NOT NULL) AS surveys,
              array_agg(DISTINCT replace(abstract, '?', '')) FILTER (WHERE abstract IS NOT NULL) AS abstracts
         FROM gis.abstracts`,
    ),
  ]);
  const entries = (rows: { name: string; n: number; ext: string | null }[]): RefEntry[] =>
    rows.map((r) => ({ name: r.name, n: r.n, bbox: parseExtent(r.ext) }));
  const w = wellAgg[0];
  const a = absAgg[0];
  // Louisiana wells (sonris.*) join the same lists: one operator list, one
  // field list, one status/type vocabulary, one well count.
  const la = sonrisWellsAvailable() ? await loadLaReference() : null;
  return {
    operators: mergeRefEntries(entries(operators), la ? entries(la.operators) : []),
    fields: mergeRefEntries(entries(fields), la ? entries(la.fields) : []),
    formations: entries(formations),
    types: [...new Set([...(w?.types ?? []), ...(la?.types ?? [])])].sort(),
    statuses: [...new Set([...(w?.statuses ?? []), ...(la?.statuses ?? [])])].sort(),
    wellCount: (w?.n ?? 0) + (la?.n ?? 0),
    surveys: (a?.surveys ?? []).sort(),
    abstracts: (a?.abstracts ?? []).sort((x, y) => x.localeCompare(y, undefined, { numeric: true })),
  };
}

/** Louisiana's share of the reference index — aggregations over sonris.wells (a few thousand rows). */
export const LA_REFERENCE_SQL = {
  agg: (col: "operator" | "field") =>
    `SELECT ${col} AS name, count(*)::int AS n, ST_Extent(geom)::text AS ext
       FROM sonris.wells WHERE ${col} IS NOT NULL AND ${col} <> '' GROUP BY ${col}`,
  vocab: `SELECT array_agg(DISTINCT type) AS types, array_agg(DISTINCT status) AS statuses, count(*)::int AS n FROM sonris.wells`,
};

async function loadLaReference() {
  type Agg = { name: string; n: number; ext: string | null };
  const [operators, fields, vocab] = await Promise.all([
    prisma.$queryRawUnsafe<Agg[]>(LA_REFERENCE_SQL.agg("operator")),
    prisma.$queryRawUnsafe<Agg[]>(LA_REFERENCE_SQL.agg("field")),
    prisma.$queryRawUnsafe<{ types: string[] | null; statuses: string[] | null; n: number }[]>(LA_REFERENCE_SQL.vocab),
  ]);
  return { operators, fields, types: vocab[0]?.types ?? [], statuses: vocab[0]?.statuses ?? [], n: vocab[0]?.n ?? 0 };
}

/**
 * Merge two reference lists by exact name (an operator active in both states
 * is ONE entry): well counts add, extents union. Order: first list, then the
 * second list's new names.
 */
export function mergeRefEntries(a: readonly RefEntry[], b: readonly RefEntry[]): RefEntry[] {
  const out = new Map<string, RefEntry>(a.map((e) => [e.name, { ...e }]));
  for (const e of b) {
    const cur = out.get(e.name);
    if (!cur) { out.set(e.name, { ...e }); continue; }
    const bb = cur.bbox && e.bbox
      ? [Math.min(cur.bbox[0], e.bbox[0]), Math.min(cur.bbox[1], e.bbox[1]), Math.max(cur.bbox[2], e.bbox[2]), Math.max(cur.bbox[3], e.bbox[3])] as [number, number, number, number]
      : cur.bbox ?? e.bbox;
    out.set(e.name, { name: e.name, n: cur.n + e.n, bbox: bb });
  }
  return [...out.values()];
}

async function referenceIndex(): Promise<WellReferenceIndex> {
  const now = Date.now();
  if (referenceCache && now - referenceCache.at < referenceCache.ttl) return referenceCache.value;
  if (referenceInFlight) return referenceInFlight;
  referenceInFlight = loadReferenceIndex()
    .then((value) => {
      referenceCache = { at: Date.now(), ttl: REFERENCE_TTL_MS, value };
      return value;
    })
    .catch((e) => {
      // Never let a missing rrc schema (dev databases) or a transient blip turn
      // the map's search box into a 500 — degrade to no suggestions, retry soon.
      console.warn("[gis] reference index load failed:", e instanceof Error ? e.message : e);
      referenceCache = { at: Date.now(), ttl: REFERENCE_ERROR_TTL_MS, value: EMPTY_REFERENCE };
      return EMPTY_REFERENCE;
    })
    .finally(() => { referenceInFlight = null; });
  return referenceInFlight;
}

/** Drop the memoized reference lists (call after an ingest re-import). */
export function invalidateReferenceIndex(): void {
  referenceCache = null;
}

/**
 * Forget everything this process memoized from the gis/rrc schemas — the tile
 * LRU and the reference index. Called after a boot-time cadastral load
 * (services/gisRegions.ts) so tiles served while it ran don't outlive it.
 */
export function clearGisCaches(): void {
  tileCache.clear();
  invalidateReferenceIndex();
}

/**
 * Unified map search: one query, every entity the map knows about — counties,
 * abstracts, surveys, wells (API #, well #, lease name/number), operators,
 * fields, formations, basins, and the org's deals & mineral assets. Each group
 * is ranked by trigram similarity and capped; the client interleaves groups.
 * Result rows carry an `action` payload the client uses to zoom/highlight or
 * apply a filter.
 */
/** "BOX(minx miny,maxx maxy)" → [minx, miny, maxx, maxy] (or null). */
export function parseExtent(ext: string | null): [number, number, number, number] | null {
  const m = ext?.match(/^BOX\(([-\d.]+) ([-\d.]+),([-\d.]+) ([-\d.]+)\)$/);
  return m ? [Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4])] : null;
}

/**
 * The multi-state /suggest queries, named so they can be exercised directly
 * against a PostGIS database. $1/$2/$3 are documented per query.
 */
export const SUGGEST_SQL = {
  /** Counties + parishes: $1 = ILIKE pattern, $2 = name term, $3 = state or NULL. */
  counties: `SELECT name, state, ST_XMin(geom) minx, ST_YMin(geom) miny, ST_XMax(geom) maxx, ST_YMax(geom) maxy
               FROM gis.counties WHERE name ILIKE $1 ESCAPE '\\' AND ($3::text IS NULL OR state = $3::text)
              ORDER BY similarity(name, $2) DESC, name, state DESC LIMIT 254`,
  /** Louisiana sections: $1 = township/range ("T17N R13W") or NULL, $2 = section number or NULL. */
  plssSections: `SELECT id, abstract, survey, county, state, 1::float8 AS score
                   FROM gis.abstracts
                  WHERE state = 'LA'
                    AND ($1::text IS NULL OR survey = $1::text)
                    AND ($2::int IS NULL OR NULLIF(regexp_replace(abstract, '[^0-9]', '', 'g'), '')::int = $2::int)
                  ORDER BY survey, NULLIF(regexp_replace(abstract, '[^0-9]', '', 'g'), '')::int NULLS LAST, county
                  LIMIT 200`,
  /** One whole township: $1 = township/range. */
  township: `SELECT survey, array_agg(DISTINCT county ORDER BY county) AS counties, count(*)::int AS n, ST_Extent(geom)::text AS ext
               FROM gis.abstracts WHERE state = 'LA' AND survey = $1::text GROUP BY survey`,
};

type LaSuggestRow = { fid: number; serial: number; api: string | null; name: string; wellNo: string | null; operator: string | null; field: string | null; luw: string | null; statusText: string; parish: string; type: string; lon: number; lat: number; score: number };

/** How many leading rows of a Louisiana suggest result are exact identifier hits (the SQL sorts them first). */
function laExact(rows: readonly LaSuggestRow[], q: string): number {
  const d = identifierDigits(q);
  if (!d) return 0;
  let n = 0;
  while (n < rows.length && (String(rows[n].serial) === d || rows[n].luw === d || (rows[n].api ?? "").startsWith(d))) n++;
  return n;
}

/** Search-result label for a Louisiana well: "NAME #003-ALT" · "Serial 253790 · API … · LUW … · operator · Red River Parish, LA". */
export function laSuggestLabel(w: Pick<LaSuggestRow, "name" | "wellNo" | "serial" | "api" | "luw" | "operator" | "parish">): { label: string; sub: string } {
  return {
    label: `${w.name}${w.wellNo ? ` #${w.wellNo}` : ""}`,
    sub: [`Serial ${w.serial}`, w.api ? `API ${w.api}` : null, w.luw ? `LUW ${w.luw}` : null, w.operator, laParishLabel(w.parish)].filter(Boolean).join(" · "),
  };
}

gisRouter.get(
  "/suggest",
  asyncHandler(async (req: AuthedRequest, res) => {
    const { q } = searchSchema.parse(req.query);
    // `%` and `_` are LIKE operators, not literals: an unescaped term made of
    // them yields a pattern with no extractable trigram, which is precisely the
    // seq scan the indexes exist to prevent. See domain/search.escapeLike.
    const like = `%${escapeLike(q)}%`;
    // "Caddo Parish" / "Sabine County, TX" name a county in a specific state;
    // a bare "Sabine" finds both the Texas county and the Louisiana parish.
    const ct = countySearchTerm(q);
    // A PLSS reference ("Sec 12 T17N R13W", "T17N R13W") resolves Louisiana
    // sections exactly — the label/survey text match below can't, since the
    // section and the township live in different columns.
    const plss = parsePlssQuery(q);

    type AbsRow = { id: string; abstract: string | null; survey: string | null; county: string; state: string | null; score: number };
    const [counties, abstracts, townships, wells, laWells, reference, deals] = await Promise.all([
      // Counties/parishes, with bbox so the client can frame them without local data.
      prisma.$queryRawUnsafe<{ name: string; state: string; minx: number; miny: number; maxx: number; maxy: number }[]>(
        SUGGEST_SQL.counties, `%${escapeLike(ct.name)}%`, ct.name, ct.state),
      plss
        // Louisiana sections by township/range and/or section number.
        ? prisma.$queryRawUnsafe<AbsRow[]>(
          SUGGEST_SQL.plssSections, plss.township, plss.section)
        // Abstract number OR survey name (both live on gis.abstracts). Labels are
        // matched and returned with the source data's stray '?' stripped.
        : prisma.$queryRawUnsafe<AbsRow[]>(
        `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, state,
                GREATEST(similarity(replace(coalesce(abstract,''), '?', ''), $2), similarity(coalesce(survey,''), $2)) AS score
           FROM gis.abstracts
          WHERE replace(abstract, '?', '') ILIKE $1 ESCAPE '\\' OR survey ILIKE $1 ESCAPE '\\'
          -- Exact abstract numbers, then numbers starting with the typed digits,
          -- survive the LIMIT ahead of mere trigram similarity ($3 = digits typed).
          ORDER BY CASE WHEN $3 = '' THEN 2
                        WHEN ltrim(regexp_replace(coalesce(abstract,''), '[^0-9]', '', 'g'), '0') = $3 THEN 0
                        WHEN ltrim(regexp_replace(coalesce(abstract,''), '[^0-9]', '', 'g'), '0') LIKE $3 || '%' THEN 1
                        ELSE 2 END,
                   score DESC, county, abstract LIMIT 200`, like, q, (q.match(/\d+/)?.[0] ?? "").replace(/^0+(?=\d)/, "")),
      // A whole PLSS township ("T17N R13W"), framed as one result.
      plss?.township
        ? prisma.$queryRawUnsafe<{ survey: string; counties: string[]; n: number; ext: string | null }[]>(
          SUGGEST_SQL.township, plss.township)
        : Promise.resolve([]),
      // Wells: API number, well number, well ID, lease name, RRC lease number.
      prisma.$queryRawUnsafe<{ fid: number; api8: string | null; wellNo: string | null; leaseName: string | null; leaseNo: string | null; operator: string | null; type: string | null; county: string; score: number }[]>(
        `SELECT fid, api8, well_no AS "wellNo", lease_name AS "leaseName", lease_no AS "leaseNo",
                operator, type, county,
                GREATEST(similarity(coalesce(api8,''), $2), similarity(coalesce(lease_name,''), $2),
                         similarity(coalesce(lease_no,''), $2)) AS score
           FROM rrc.wells
          WHERE api8 LIKE $1 ESCAPE '\\' OR api10 LIKE $1 ESCAPE '\\'
             OR lease_name ILIKE $1 ESCAPE '\\' OR lease_no LIKE $1 ESCAPE '\\'
             OR well_id ILIKE $1 ESCAPE '\\' OR well_no = upper($2)
          ORDER BY score DESC, county, lease_name NULLS LAST LIMIT 200`, like, q),
      // Louisiana wells: name, serial, API, LUW (unit), operator and field.
      sonrisWellsAvailable()
        ? prisma.$queryRawUnsafe<LaSuggestRow[]>(LA_WELL_SQL.suggest, like, q, identifierDigits(q))
        : Promise.resolve([] as LaSuggestRow[]),
      // Operators, fields and formations come from the precomputed reference
      // index and are ranked in memory — see WellReferenceIndex above for why
      // these three cannot remain per-request aggregations.
      referenceIndex(),
      // The org's deals and mineral assets, matched on name or basin. Basin
      // itself has no geometry — matching deals stand in for it.
      prisma.deal.findMany({
        where: {
          organizationId: orgId(req),
          OR: [{ name: { contains: q, mode: "insensitive" } }, { basins: { has: q } }],
        },
        select: { id: true, name: true, recordType: true, stage: true, counties: true, abstractIds: true, basins: true },
        orderBy: { updatedAt: "desc" },
        take: 100,
      }),
    ]);

    res.json({
      // "Leon County, TX" / "Caddo Parish, LA" — the state tells Sabine TX from Sabine LA.
      counties: counties.map((c) => ({
        label: `${countyLabel(c.name, c.state)}, ${c.state}`,
        sub: `Go to ${countyNoun(c.state).toLowerCase()}`,
        key: countyKey(c.name, c.state),
        bbox: [c.minx, c.miny, c.maxx, c.maxy],
      })),
      // Number-first ranking (exact abstract # → prefix → contains → survey
      // text, ascending by number within each) so "15" puts Abstract 15 on top.
      // PLSS results arrive already ordered by township and section number.
      abstracts: (plss ? abstracts : rankAbstracts(abstracts, q, (a) => ({ abstract: a.abstract ?? a.id, text: `${a.abstract ?? ""} ${a.survey ?? ""} ${a.county}` })))
        .map((a) => (a.state === "LA" || isSectionLabel(a.abstract)
          // A Louisiana PLSS section: "Sec 12 · T17N R13W" in "Caddo Parish, Louisiana".
          ? { id: a.id, label: sectionLabel(a), sub: countyStateLabel(a.county, a.state ?? "LA") }
          : {
            id: a.id,
            label: `Abstract ${abstractNumber(a.abstract ?? a.id)}`,
            sub: [surveyLabel(a.survey), countyStateLabel(a.county, a.state ?? "TX")].filter(Boolean).join(" · "),
          })),
      townships: townships.map((t) => ({
        label: t.survey,
        sub: `Township · ${t.counties.map((c) => countyLabel(c, "LA")).join(", ")}, LA · ${t.n} section${t.n === 1 ? "" : "s"}`,
        bbox: parseExtent(t.ext),
      })),
      // Texas and Louisiana wells, one list ranked by match score.
      wells: [
        ...wells.map((w) => ({
          fid: w.fid, score: Number(w.score),
          label: `${w.leaseName ?? "Well"}${w.wellNo ? ` #${w.wellNo}` : ""}`,
          sub: [w.api8 ? `API ${w.api8}` : null, w.leaseNo ? `Lease ${w.leaseNo}` : null, w.operator, `${w.county} County`].filter(Boolean).join(" · "),
        })),
        ...laWells.map((w, i) => ({
          // An exact serial / LUW / API hit outranks any similarity score.
          fid: w.fid, score: i < laExact(laWells, q) ? 2 : Number(w.score),
          ...laSuggestLabel(w),
        })),
      ].sort((a, b) => b.score - a.score).slice(0, 200).map(({ score: _score, ...w }) => w),
      operators: rankRefEntries(reference.operators, q, 100).map((o) => ({ name: o.name, sub: `${o.n} wells · filters the map`, bbox: o.bbox })),
      fields: rankRefEntries(reference.fields, q, 100).map((f) => ({ name: f.name, sub: `${f.n} wells`, bbox: f.bbox })),
      formations: rankRefEntries(reference.formations, q, 100).map((f) => ({ name: f.name, sub: `${f.n} wells · filters the map`, bbox: f.bbox })),
      deals: deals.filter((d) => d.recordType !== "OWNED_ASSET").map((d) => ({
        id: d.id, label: d.name, abstractIds: d.abstractIds,
        sub: [d.stage, d.counties.join(", "), d.basins.join(", ")].filter(Boolean).join(" · "),
      })),
      assets: deals.filter((d) => d.recordType === "OWNED_ASSET").map((d) => ({
        id: d.id, label: d.name, abstractIds: d.abstractIds,
        sub: [d.counties.join(", "), d.basins.join(", ")].filter(Boolean).join(" · "),
      })),
    });
  }),
);

/** Abstract/survey search across every imported county (trigram-indexed). */
gisRouter.get(
  "/search",
  asyncHandler(async (req, res) => {
    const { q } = searchSchema.parse(req.query);
    const rows = await prisma.$queryRawUnsafe<
      { id: string; abstract: string | null; survey: string | null; county: string; state: string; lon: number; lat: number }[]
    >(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, state,
              ST_X(ST_PointOnSurface(geom)) AS lon, ST_Y(ST_PointOnSurface(geom)) AS lat
         FROM gis.abstracts
        WHERE replace(abstract, '?', '') ILIKE $1 ESCAPE '\\' OR survey ILIKE $1 ESCAPE '\\'
        ORDER BY GREATEST(similarity(replace(coalesce(abstract, ''), '?', ''), $2), similarity(coalesce(survey, ''), $2)) DESC,
                 county, abstract
        LIMIT 100`,
      `%${escapeLike(q)}%`, q,
    );
    res.json(rows);
  }),
);

/** Well search: API number, well name/lease, or operator (rrc.wells). */
gisRouter.get(
  "/wells/search",
  asyncHandler(async (req, res) => {
    const { q } = searchSchema.parse(req.query);
    const rows = await prisma.$queryRawUnsafe<
      { fid: number; api8: string | null; wellNo: string | null; leaseName: string | null; operator: string | null; type: string | null; county: string; lon: number; lat: number }[]
    >(
      `SELECT fid, api8, well_no AS "wellNo", lease_name AS "leaseName", operator, type, county,
              ST_X(geom) AS lon, ST_Y(geom) AS lat
         FROM rrc.wells
        WHERE api8 LIKE $1 ESCAPE '\\' OR api10 LIKE $1 ESCAPE '\\'
           OR lease_name ILIKE $1 ESCAPE '\\' OR operator ILIKE $1 ESCAPE '\\'
           OR well_no = upper($2)
        ORDER BY county, lease_name NULLS LAST
        LIMIT 100`,
      `%${escapeLike(q)}%`, q,
    );
    // Louisiana wells in the same row shape (lease name = the state's well name).
    const la = sonrisWellsAvailable()
      ? (await prisma.$queryRawUnsafe<LaSuggestRow[]>(LA_WELL_SQL.suggest, `%${escapeLike(q)}%`, q, identifierDigits(q)))
        .map((w) => ({ fid: w.fid, api8: null, wellNo: w.wellNo, leaseName: w.name, operator: w.operator, type: w.type, county: w.parish, state: "LA", lon: w.lon, lat: w.lat }))
      : [];
    res.json([...rows, ...la]);
  }),
);

/** Full well detail for the map panel, including permits and completions. */
gisRouter.get(
  "/wells/:fid",
  asyncHandler(async (req, res) => {
    const fid = Number(req.params.fid);
    if (!Number.isInteger(fid)) return res.status(400).json({ error: "invalid fid" });
    // A Louisiana fid (2e9 + serial) is a SONRIS well — its own record, with
    // its unit's production instead of RRC permits/completions.
    if (isLaFid(fid)) {
      const la = sonrisWellsAvailable() ? await laWellDetail(fid) : null;
      if (!la) return res.status(404).json({ error: "well not found" });
      return res.json(la);
    }
    const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
      `SELECT fid, api8, api10 AS api, well_no AS "wellNo", well_id AS "wellId", symbol, type, status,
              county, district, lease_no AS "leaseNo", lease_name AS "leaseName",
              operator, operator_no AS "operatorNo", field_no AS "fieldNo", field_name AS field,
              oil_gas AS "oilGas", formations, spud_date AS "spudDate", plug_date AS "plugDate",
              cum_oil AS "cumOil", cum_gas AS "cumGas", last_prod AS "lastProd",
              replace(abstract, '?', '') AS abstract, survey, abstract_id AS "abstractId",
              ST_X(geom) AS lon, ST_Y(geom) AS lat
         FROM rrc.wells WHERE fid = $1`,
      fid,
    );
    if (!rows.length) return res.status(404).json({ error: "well not found" });
    const well = rows[0];
    const [permits, completions, unitAcresRow] = await Promise.all([
      prisma.$queryRawUnsafe<Record<string, unknown>[]>(
        `SELECT status_no AS "statusNo", permit_date AS "permitDate", operator, lease_name AS "leaseName", well_no AS "wellNo", acres::float8 AS acres, survey, abstract
           FROM rrc.permits WHERE api8 = $1 ORDER BY permit_date DESC NULLS LAST LIMIT 12`,
        String(well.api8 ?? "")),
      prisma.$queryRawUnsafe<Record<string, unknown>[]>(
        `SELECT tracking_no AS "trackingNo", filing_type AS "filingType", status,
                filed_date AS "filedDate", completion_date AS "completionDate", field_name AS "fieldName"
           FROM rrc.completions WHERE api8 = $1 ORDER BY filed_date DESC NULLS LAST LIMIT 12`,
        String(well.api8 ?? "")),
      // Unit size: the W-1 lease/pooled-unit acreage from the well's most
      // recent permit that reported one (older filings often left it zero).
      prisma.$queryRawUnsafe<{ acres: number }[]>(
        `SELECT acres::float8 AS acres FROM rrc.permits
          WHERE api8 = $1 AND acres IS NOT NULL
          ORDER BY permit_date DESC NULLS LAST LIMIT 1`,
        String(well.api8 ?? "")),
    ]);
    res.json({ ...well, permits, completions, unitAcres: unitAcresRow[0]?.acres ?? null });
  }),
);

// Bound the raw string so a pathological county list can't build a giant
// ANY($1::text[]) array; the names are sliced again below as defense in depth.
const optionsSchema = z.object({ counties: z.string().max(4000).optional() });

/**
 * Survey/abstract filter option lists, optionally scoped to counties
 * (comma-separated county keys: "Leon" = Texas, "LA|Caddo" = a Louisiana
 * parish — see domain/gisRegion). Replaces the client building these from
 * downloaded GeoJSON.
 */
gisRouter.get(
  "/options",
  asyncHandler(async (req, res) => {
    const { counties } = optionsSchema.parse(req.query);
    const names = (counties ?? "").split(",").map((s) => s.trim()).filter(Boolean).slice(0, 500);

    // No county selected — every query below degrades to a full scan with a
    // DISTINCT/array_agg over the whole table, and the map issues this on load.
    // That statewide answer is identical for every caller and changes only on
    // ingest, so serve it from the same precomputed index /suggest uses.
    if (!names.length) {
      const ref = await referenceIndex();
      res.json({
        surveys: ref.surveys,
        abstracts: ref.abstracts,
        wellTypes: ref.types,
        wellStatuses: ref.statuses,
        operators: ref.operators.map((o) => o.name).sort(),
        wellCount: ref.wellCount,
      });
      return;
    }

    // County-scoped: these ride the county btree, so they stay live queries.
    // State-qualified, so Sabine TX and Sabine LA never mix.
    const params: unknown[] = [];
    const scope = `${countyScopePredicate(names, params)} AND`;
    const surveys = await prisma.$queryRawUnsafe<{ v: string }[]>(
      `SELECT DISTINCT survey AS v FROM gis.abstracts WHERE ${scope} survey IS NOT NULL ORDER BY v`,
      ...params,
    );
    const abstracts = await prisma.$queryRawUnsafe<{ v: string }[]>(
      `SELECT DISTINCT replace(abstract, '?', '') AS v FROM gis.abstracts WHERE ${scope} abstract IS NOT NULL ORDER BY v`,
      ...params,
    );
    // Well-derived filter option lists from rrc.wells (RRC = Texas only), so
    // only the Texas counties among the selection can scope them…
    const txNames = texasCountyNames(names);
    const wellAgg = txNames.length
      ? await prisma.$queryRawUnsafe<{ types: string[]; statuses: string[]; operators: string[]; n: number }[]>(
        `SELECT array_agg(DISTINCT type) FILTER (WHERE type IS NOT NULL) AS types,
                array_agg(DISTINCT status) FILTER (WHERE status IS NOT NULL) AS statuses,
                array_agg(DISTINCT operator) FILTER (WHERE operator IS NOT NULL) AS operators,
                count(*)::int AS n
           FROM rrc.wells WHERE county = ANY($1::text[])`,
        txNames,
      )
      : [];
    // …and Louisiana parishes scope sonris.wells (SONRIS = Louisiana) the same way.
    const laNames = sonrisWellsAvailable() ? louisianaParishNames(names) : [];
    const laAgg = laNames.length
      ? await prisma.$queryRawUnsafe<{ types: string[] | null; statuses: string[] | null; operators: string[] | null; n: number }[]>(
        `SELECT array_agg(DISTINCT type) FILTER (WHERE type IS NOT NULL) AS types,
                array_agg(DISTINCT status) FILTER (WHERE status IS NOT NULL) AS statuses,
                array_agg(DISTINCT operator) FILTER (WHERE operator IS NOT NULL) AS operators,
                count(*)::int AS n
           FROM sonris.wells WHERE parish = ANY($1::text[])`,
        laNames,
      )
      : [];
    const w = wellAgg[0];
    const l = laAgg[0];
    const union = (a?: string[] | null, b?: string[] | null) => [...new Set([...(a ?? []), ...(b ?? [])])].sort();
    res.json({
      surveys: surveys.map((r) => r.v),
      abstracts: abstracts.map((r) => r.v).sort((a, b) => a.localeCompare(b, undefined, { numeric: true })),
      wellTypes: union(w?.types, l?.types),
      wellStatuses: union(w?.statuses, l?.statuses),
      operators: union(w?.operators, l?.operators),
      wellCount: (w?.n ?? 0) + (l?.n ?? 0),
    });
  }),
);

/**
 * Bounding box of everything matching the current map filters — powers the
 * map's "zoom to filtered results" behavior. Filter values arrive as repeated
 * query params (?operators=A&operators=B) because operator names can contain
 * commas. Precedence: any well-level filter (type/status/operator) frames the
 * matching wells; otherwise abstract/survey filters frame matching abstracts;
 * otherwise the selected counties frame themselves. County values are
 * state-qualified keys (domain/gisRegion: "Leon", "LA|Caddo").
 */
/**
 * Pure query planner for /extent (exported for tests): picks the table whose
 * extent best represents "the filtered results" and builds the parameterized
 * predicate list. Returns null when no filter is set.
 */
export function planExtentQuery(q: Record<string, unknown>, opts: { sonris?: boolean } = {}): { sql: string; params: string[][] } | null {
  const list = (k: string): string[] =>
    (Array.isArray(q[k]) ? (q[k] as unknown[]) : q[k] == null ? [] : [q[k]])
      .map((s) => String(s).trim()).filter(Boolean).slice(0, 500);
  const states = list("states"), counties = list("counties"), surveys = list("surveys"), abstracts = list("abstracts");
  const wellTypes = list("wellTypes"), wellStatuses = list("wellStatuses"), operators = list("operators");

  const params: string[][] = [];
  const cond = (col: string, vals: string[]): string => { params.push(vals); return `${col} = ANY($${params.length}::text[])`; };

  if (wellTypes.length || wellStatuses.length || operators.length) {
    const conds: string[] = [];
    // rrc.wells is Texas-only (RRC): a Louisiana parish matches no well there.
    if (counties.length) conds.push(cond("county", texasCountyNames(counties)));
    if (surveys.length) conds.push(cond("survey", surveys));
    if (abstracts.length) conds.push(cond("replace(abstract, '?', '')", abstracts));
    if (wellTypes.length) conds.push(cond("type", wellTypes));
    if (wellStatuses.length) conds.push(cond("status", wellStatuses));
    if (operators.length) conds.push(cond("operator", operators));
    if (!opts.sonris) return { sql: `SELECT ST_Extent(geom)::text AS ext FROM rrc.wells WHERE ${conds.join(" AND ")}`, params };
    // Louisiana wells (sonris.wells) by the same filters: parishes by name,
    // townships as surveys, "Sec N" as abstracts.
    const la: string[] = [];
    if (counties.length) la.push(cond("parish", louisianaParishNames(counties)));
    if (surveys.length) la.push(cond("township", surveys));
    if (abstracts.length) la.push(cond("('Sec ' || section)", abstracts));
    if (wellTypes.length) la.push(cond("type", wellTypes));
    if (wellStatuses.length) la.push(cond("status", wellStatuses));
    if (operators.length) la.push(cond("operator", operators));
    return {
      sql: `SELECT ST_Extent(geom)::text AS ext FROM (
              SELECT geom FROM rrc.wells WHERE ${conds.join(" AND ")}
              UNION ALL
              SELECT geom FROM sonris.wells WHERE ${la.join(" AND ")}) u`,
      params,
    };
  }
  if (surveys.length || abstracts.length) {
    const conds: string[] = [];
    if (counties.length) conds.push(countyScopePredicate(counties, params));
    if (surveys.length) conds.push(cond("survey", surveys));
    if (abstracts.length) conds.push(cond("replace(abstract, '?', '')", abstracts));
    return { sql: `SELECT ST_Extent(geom)::text AS ext FROM gis.abstracts WHERE ${conds.join(" AND ")}`, params };
  }
  if (counties.length) {
    return { sql: `SELECT ST_Extent(geom)::text AS ext FROM gis.counties WHERE ${countyScopePredicate(counties, params, { state: "state", county: "name" })}`, params };
  }
  // State filter alone: frame the selected states' coverage (Texas counties,
  // Louisiana's Haynesville parishes). A selection with no GIS coverage has
  // nothing to frame.
  if (states.length) {
    const covered = [...new Set(states.map((s) => s.toUpperCase()))].filter((s) => (GIS_STATES as readonly string[]).includes(s));
    if (!covered.length) return null;
    return { sql: `SELECT ST_Extent(geom)::text AS ext FROM gis.counties WHERE ${cond("state", covered)}`, params };
  }
  return null;
}

gisRouter.get(
  "/extent",
  asyncHandler(async (req, res) => {
    const plan = planExtentQuery(req.query as Record<string, unknown>, { sonris: sonrisWellsAvailable() });
    if (!plan) return res.json({ bbox: null });
    const rows = await prisma.$queryRawUnsafe<{ ext: string | null }[]>(plan.sql, ...plan.params);
    res.json({ bbox: parseExtent(rows[0]?.ext ?? null) });
  }),
);

/**
 * Flat abstract index for the deal abstract picker (id → label mapping).
 * ~11k rows at 12 counties — fine for a one-shot cached fetch; this becomes a
 * proper search endpoint before the statewide import lands.
 */
gisRouter.get(
  "/abstracts-index",
  asyncHandler(async (_req, res) => {
    const rows = await prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; countyFips: string; state: string | null }[]>(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, county_fips AS "countyFips", state FROM gis.abstracts ORDER BY county, abstract`,
    );
    // Shared, org-independent reference geometry — safe to cache so this full
    // ~11k-row fetch isn't repeated on every map load.
    res.setHeader("Cache-Control", "public, max-age=3600");
    res.json(rows);
  }),
);

/** Full geometry for a small set of abstracts (deal footprint rendering). */
gisRouter.get(
  "/features",
  asyncHandler(async (req, res) => {
    const ids = String(req.query.ids ?? "").split(",").map((s) => s.trim()).filter(Boolean).slice(0, 500);
    if (!ids.length) return res.json({ type: "FeatureCollection", features: [] });
    const rows = await prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; state: string; area: number | null; geom: string }[]>(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, state, area_m2 AS area, ST_AsGeoJSON(geom, 6) AS geom
         FROM gis.abstracts WHERE id = ANY($1::text[])`,
      ids,
    );
    res.json({
      type: "FeatureCollection",
      features: rows.map((r) => ({
        type: "Feature",
        properties: { id: r.id, abstract: r.abstract, survey: r.survey, county: r.county, state: r.state, area: r.area },
        geometry: JSON.parse(r.geom) as unknown,
      })),
    });
  }),
);

/**
 * Lease-level monthly production for a county (B5: rrc.production, from the
 * PDQ dump). Response matches the shape of the old static
 * /data/{county}-production.json assets so the heat-map pipeline and the
 * well-panel chart consume it unchanged:
 *   { "OG|district|leaseNo": [[yyyymm, oil_bbl, gas_mcf], ...], ... }
 * Oil includes condensate; gas includes casinghead. Months with no reported
 * volume are simply absent (zeros are dropped at import).
 */
const productionSchema = z.object({
  county: z.string().trim().min(1).max(40),
  months: z.coerce.number().int().min(1).max(1200).default(120),
});
gisRouter.get(
  "/production",
  asyncHandler(async (req, res) => {
    const { county, months } = productionSchema.parse(req.query);
    // Anchor the window to the latest reported month, not the calendar —
    // RRC production lags 2–4 months.
    const latest = await prisma.$queryRawUnsafe<{ mx: number | null }[]>(
      `SELECT max(cycle_ym)::int AS mx FROM rrc.production WHERE county = $1`, county);
    const mx = latest[0]?.mx;
    if (!mx) return res.json({});
    const y = Math.floor(mx / 100), m = mx % 100;
    const total = y * 12 + (m - 1) - (months - 1);
    const from = Math.floor(total / 12) * 100 + (total % 12) + 1;
    const rows = await prisma.$queryRawUnsafe<
      { key: string; ym: number; oil: number; gas: number }[]
    >(
      `SELECT og_code || '|' || district || '|' || lease_no AS key, cycle_ym AS ym,
              sum(oil_bbl + cond_bbl)::int AS oil, sum(gas_mcf + csgd_mcf)::int AS gas
         FROM rrc.production
        WHERE county = $1 AND cycle_ym >= $2
        GROUP BY 1, 2 ORDER BY 1, 2`,
      county, from,
    );
    const out: Record<string, [number, number, number][]> = {};
    for (const r of rows) (out[r.key] ??= []).push([r.ym, r.oil, r.gas]);
    res.setHeader("Cache-Control", "private, max-age=3600");
    res.json(out);
  }),
);

/** Bounding box + feature detail for one abstract (used to frame selections). */
gisRouter.get(
  "/abstracts/:id",
  asyncHandler(async (req, res) => {
    const rows = await prisma.$queryRawUnsafe<
      { id: string; abstract: string | null; survey: string | null; county: string; state: string; minx: number; miny: number; maxx: number; maxy: number }[]
    >(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, state,
              ST_XMin(geom) AS minx, ST_YMin(geom) AS miny, ST_XMax(geom) AS maxx, ST_YMax(geom) AS maxy
         FROM gis.abstracts WHERE id = $1`,
      String(req.params.id),
    );
    if (!rows.length) return res.status(404).json({ error: "abstract not found" });
    res.json(rows[0]);
  }),
);
