import { Router } from "express";
import { z } from "zod";
import { prisma, withDbRetry } from "../db.js";
import { asyncHandler } from "../middleware/errors.js";
import { requireAuth, requireOrg, requirePermission, orgId, type AuthedRequest } from "../middleware/auth.js";

/**
 * GIS Phase A (see docs/architecture/0003-gis-scale-architecture.md).
 *
 * Cadastral data lives in PostGIS (`gis` schema on the existing Neon DB) and is
 * delivered to MapLibre as vector tiles generated by ST_AsMVT. Search and
 * filter-option lists are trigram-backed queries — the client no longer needs
 * any abstract data downloaded to search or filter it.
 *
 * Tiles are mounted un-authed: MapLibre tile requests don't carry the
 * Authorization header, and the payload is public-record survey geometry
 * (same data UT BEG serves publicly). Everything org- or deal-related stays
 * on the authed routers.
 */

const TILE_EXTENT = 4096;
const TILE_BUFFER = 64;
/** County boundaries (full-resolution TIGER) serve at every zoom; denser
 * layers gate in as their content becomes legible. Statewide, a z7 tile would
 * carry 15–20k abstracts (~2 MB) — too slow to generate and pointless to
 * render — so abstract detail starts at z8. */
const TILE_MIN_ZOOM = 0;
const TILE_MAX_ZOOM = 22;
const ABSTRACTS_MIN_ZOOM = 8;
/** Well points/laterals only render usefully once zoomed in; gating them here
 * keeps low-zoom tiles slim (a dense county can hold 10k+ wells). */
const WELLS_MIN_ZOOM = 9;
const BORES_MIN_ZOOM = 10;

// Tiny insertion-order LRU. Cadastral data changes only on re-import, so a
// process-lifetime cache is safe; Railway redeploys (and imports precede
// deploys) naturally flush it.
const tileCache = new Map<string, Buffer>();
const TILE_CACHE_MAX = 800;
function cachePut(key: string, buf: Buffer): void {
  if (tileCache.size >= TILE_CACHE_MAX) {
    const oldest = tileCache.keys().next().value;
    if (oldest !== undefined) tileCache.delete(oldest);
  }
  tileCache.set(key, buf);
}
/** Get + refresh recency (true LRU): hot tiles survive pans across the state. */
function cacheGet(key: string): Buffer | undefined {
  const hit = tileCache.get(key);
  if (hit) { tileCache.delete(key); tileCache.set(key, hit); }
  return hit;
}

export const gisTilesRouter = Router();

gisTilesRouter.get(
  "/:z/:x/:y.pbf",
  asyncHandler(async (req, res) => {
    const z = Number(req.params.z), x = Number(req.params.x), y = Number(req.params.y);
    if (!Number.isInteger(z) || !Number.isInteger(x) || !Number.isInteger(y) || z < 0 || z > TILE_MAX_ZOOM || x < 0 || y < 0 || x >= 2 ** z || y >= 2 ** z) {
      return res.status(400).json({ error: "invalid tile coordinates" });
    }
    res.setHeader("Content-Type", "application/x-protobuf");
    res.setHeader("Cache-Control", "public, max-age=3600");
    if (z < TILE_MIN_ZOOM) return res.status(204).end();

    const key = `${z}/${x}/${y}`;
    const hit = cacheGet(key);
    if (hit) return res.send(hit);

    // Bbox filter runs against the 4326 GIST indexes; only intersecting rows
    // get transformed/clipped. ST_AsMVTGeom quantizes to the tile grid, so
    // payload size tracks the viewport, not the tables. An MVT is a protobuf
    // whose layers are independent messages, so concatenating per-layer
    // ST_AsMVT buffers yields one multi-layer tile. Wellbore rows join their
    // surface well's attributes so the client can apply identical filter
    // expressions to both layers.
    //
    // Wrapped in withDbRetry: this route is un-authed and high-frequency, so it
    // is the one most likely to catch a transient Neon reconnect blip (P1001).
    // The retry is happy-path-transparent — the query runs once when the DB is
    // reachable, and only re-runs on a connection error.
    const rows = await withDbRetry(() =>
      prisma.$queryRawUnsafe<{ tile: Buffer | null }[]>(
      `WITH bounds AS (SELECT ST_TileEnvelope($1::int, $2::int, $3::int) AS env),
       wanted AS (SELECT ST_Transform(ST_Expand(env, 4000), 4326) AS box, env FROM bounds),
       cty_mvt AS (
         SELECT ST_AsMVTGeom(ST_Transform(c.geom, 3857), w.env, ${TILE_EXTENT}, ${TILE_BUFFER}, true) AS geom,
                c.fips, c.name
           FROM gis.counties c, wanted w WHERE c.geom && w.box
       ),
       abs_mvt AS (
         SELECT ST_AsMVTGeom(ST_Transform(a.geom, 3857), w.env, ${TILE_EXTENT}, ${TILE_BUFFER}, true) AS geom,
                a.id, a.county, replace(a.abstract, '?', '') AS abstract, a.survey, a.area_m2 AS area
           FROM gis.abstracts a, wanted w WHERE a.geom && w.box
       ),
       well_mvt AS (
         SELECT ST_AsMVTGeom(ST_Transform(wl.geom, 3857), w.env, ${TILE_EXTENT}, ${TILE_BUFFER}, true) AS geom,
                wl.fid, wl.api8, wl.well_no AS "wellNo", wl.symbol, wl.type, wl.status,
                wl.county, wl.operator, replace(wl.abstract, '?', '') AS abstract, wl.survey
           FROM rrc.wells wl, wanted w WHERE wl.geom && w.box
       ),
       bore_mvt AS (
         SELECT ST_AsMVTGeom(ST_Transform(b.geom, 3857), w.env, ${TILE_EXTENT}, ${TILE_BUFFER}, true) AS geom,
                b.fid, b.surface_fid AS "surfaceId", b.wellbore_type AS "wellboreType",
                sw.type, sw.status, sw.county, sw.operator, replace(sw.abstract, '?', '') AS abstract, sw.survey
           FROM rrc.wellbores b
           LEFT JOIN rrc.wells sw ON sw.fid = b.surface_fid, wanted w
          WHERE b.geom && w.box
       )
       SELECT coalesce((SELECT ST_AsMVT(cty_mvt, 'counties', ${TILE_EXTENT}, 'geom') FROM cty_mvt WHERE geom IS NOT NULL), ''::bytea)
           || CASE WHEN $1::int >= ${ABSTRACTS_MIN_ZOOM} THEN coalesce((SELECT ST_AsMVT(abs_mvt, 'abstracts', ${TILE_EXTENT}, 'geom') FROM abs_mvt WHERE geom IS NOT NULL), ''::bytea) ELSE ''::bytea END
           || CASE WHEN $1::int >= ${WELLS_MIN_ZOOM} THEN coalesce((SELECT ST_AsMVT(well_mvt, 'wells', ${TILE_EXTENT}, 'geom') FROM well_mvt WHERE geom IS NOT NULL), ''::bytea) ELSE ''::bytea END
           || CASE WHEN $1::int >= ${BORES_MIN_ZOOM} THEN coalesce((SELECT ST_AsMVT(bore_mvt, 'wellbores', ${TILE_EXTENT}, 'geom') FROM bore_mvt WHERE geom IS NOT NULL), ''::bytea) ELSE ''::bytea END AS tile`,
      z, x, y,
    ));
    const tile = rows[0]?.tile;
    if (!tile || tile.length === 0) return res.status(204).end();
    cachePut(key, tile);
    res.send(tile);
  }),
);

export const gisRouter = Router();
gisRouter.use(requireAuth, requireOrg, requirePermission("viewMap"));

const searchSchema = z.object({ q: z.string().trim().min(1).max(120) });

/**
 * Unified map search: one query, every entity the map knows about — counties,
 * abstracts, surveys, wells (API #, well #, lease name/number), operators,
 * fields, formations, basins, and the org's deals & mineral assets. Each group
 * is ranked by trigram similarity and capped; the client interleaves groups.
 * Result rows carry an `action` payload the client uses to zoom/highlight or
 * apply a filter.
 */
/** "BOX(minx miny,maxx maxy)" → [minx, miny, maxx, maxy] (or null). */
export function parseExtent(ext: string | null): [number, number, number, number] | null {
  const m = ext?.match(/^BOX\(([-\d.]+) ([-\d.]+),([-\d.]+) ([-\d.]+)\)$/);
  return m ? [Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4])] : null;
}

gisRouter.get(
  "/suggest",
  asyncHandler(async (req: AuthedRequest, res) => {
    const { q } = searchSchema.parse(req.query);
    const like = `%${q}%`;

    const [counties, abstracts, wells, operators, fields, formations, deals] = await Promise.all([
      // Counties, with bbox so the client can frame them without local data.
      prisma.$queryRawUnsafe<{ name: string; minx: number; miny: number; maxx: number; maxy: number }[]>(
        `SELECT name, ST_XMin(geom) minx, ST_YMin(geom) miny, ST_XMax(geom) maxx, ST_YMax(geom) maxy
           FROM gis.counties WHERE name ILIKE $1
          ORDER BY similarity(name, $2) DESC, name LIMIT 254`, like, q),
      // Abstract number OR survey name (both live on gis.abstracts). Labels are
      // matched and returned with the source data's stray '?' stripped.
      prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; score: number }[]>(
        `SELECT id, replace(abstract, '?', '') AS abstract, survey, county,
                GREATEST(similarity(replace(coalesce(abstract,''), '?', ''), $2), similarity(coalesce(survey,''), $2)) AS score
           FROM gis.abstracts
          WHERE replace(abstract, '?', '') ILIKE $1 OR survey ILIKE $1
          ORDER BY score DESC, county, abstract LIMIT 200`, like, q),
      // Wells: API number, well number, well ID, lease name, RRC lease number.
      prisma.$queryRawUnsafe<{ fid: number; api8: string | null; wellNo: string | null; leaseName: string | null; leaseNo: string | null; operator: string | null; type: string | null; county: string; score: number }[]>(
        `SELECT fid, api8, well_no AS "wellNo", lease_name AS "leaseName", lease_no AS "leaseNo",
                operator, type, county,
                GREATEST(similarity(coalesce(api8,''), $2), similarity(coalesce(lease_name,''), $2),
                         similarity(coalesce(lease_no,''), $2)) AS score
           FROM rrc.wells
          WHERE api8 LIKE $1 OR api10 LIKE $1 OR lease_name ILIKE $1 OR lease_no LIKE $1
             OR well_id ILIKE $1 OR well_no = upper($2)
          ORDER BY score DESC, county, lease_name NULLS LAST LIMIT 200`, like, q),
      // Operators — resolve to a map filter + zoom to their wells' extent.
      prisma.$queryRawUnsafe<{ name: string; n: number; ext: string | null }[]>(
        `SELECT operator AS name, count(*)::int AS n, ST_Extent(geom)::text AS ext FROM rrc.wells
          WHERE operator ILIKE $1 GROUP BY operator
          ORDER BY similarity(operator, $2) DESC, n DESC LIMIT 100`, like, q),
      // Fields (RRC reservoir proxy) — zoom to the field's well extent.
      prisma.$queryRawUnsafe<{ name: string; n: number; ext: string | null }[]>(
        `SELECT field_name AS name, count(*)::int AS n, ST_Extent(geom)::text AS ext FROM rrc.wells
          WHERE field_name ILIKE $1 GROUP BY field_name
          ORDER BY similarity(field_name, $2) DESC, n DESC LIMIT 100`, like, q),
      // Formations (from W-2/G-1 completion filings on wells).
      prisma.$queryRawUnsafe<{ name: string; n: number; ext: string | null }[]>(
        `SELECT f AS name, count(*)::int AS n, ST_Extent(geom)::text AS ext
           FROM rrc.wells, unnest(formations) AS f
          WHERE f ILIKE $1 GROUP BY f
          ORDER BY similarity(f, $2) DESC, n DESC LIMIT 100`, like, q),
      // The org's deals and mineral assets, matched on name or basin. Basin
      // itself has no geometry — matching deals stand in for it.
      prisma.deal.findMany({
        where: {
          organizationId: orgId(req),
          OR: [{ name: { contains: q, mode: "insensitive" } }, { basins: { has: q } }],
        },
        select: { id: true, name: true, recordType: true, stage: true, counties: true, abstractIds: true, basins: true },
        orderBy: { updatedAt: "desc" },
        take: 100,
      }),
    ]);

    res.json({
      counties: counties.map((c) => ({ label: `${c.name} County`, bbox: [c.minx, c.miny, c.maxx, c.maxy] })),
      abstracts: abstracts.map((a) => ({ id: a.id, label: a.abstract ?? a.id, sub: [a.survey, `${a.county} County`].filter(Boolean).join(" · ") })),
      wells: wells.map((w) => ({
        fid: w.fid,
        label: `${w.leaseName ?? "Well"}${w.wellNo ? ` #${w.wellNo}` : ""}`,
        sub: [w.api8 ? `API ${w.api8}` : null, w.leaseNo ? `Lease ${w.leaseNo}` : null, w.operator, `${w.county} County`].filter(Boolean).join(" · "),
      })),
      operators: operators.map((o) => ({ name: o.name, sub: `${o.n} wells · filters the map`, bbox: parseExtent(o.ext) })),
      fields: fields.map((f) => ({ name: f.name, sub: `${f.n} wells`, bbox: parseExtent(f.ext) })),
      formations: formations.map((f) => ({ name: f.name, sub: `${f.n} wells · filters the map`, bbox: parseExtent(f.ext) })),
      deals: deals.filter((d) => d.recordType !== "OWNED_ASSET").map((d) => ({
        id: d.id, label: d.name, abstractIds: d.abstractIds,
        sub: [d.stage, d.counties.join(", "), d.basins.join(", ")].filter(Boolean).join(" · "),
      })),
      assets: deals.filter((d) => d.recordType === "OWNED_ASSET").map((d) => ({
        id: d.id, label: d.name, abstractIds: d.abstractIds,
        sub: [d.counties.join(", "), d.basins.join(", ")].filter(Boolean).join(" · "),
      })),
    });
  }),
);

/** Abstract/survey search across every imported county (trigram-indexed). */
gisRouter.get(
  "/search",
  asyncHandler(async (req, res) => {
    const { q } = searchSchema.parse(req.query);
    const rows = await prisma.$queryRawUnsafe<
      { id: string; abstract: string | null; survey: string | null; county: string; lon: number; lat: number }[]
    >(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county,
              ST_X(ST_PointOnSurface(geom)) AS lon, ST_Y(ST_PointOnSurface(geom)) AS lat
         FROM gis.abstracts
        WHERE replace(abstract, '?', '') ILIKE '%' || $1 || '%' OR survey ILIKE '%' || $1 || '%'
        ORDER BY GREATEST(similarity(replace(coalesce(abstract, ''), '?', ''), $1), similarity(coalesce(survey, ''), $1)) DESC,
                 county, abstract
        LIMIT 100`,
      q,
    );
    res.json(rows);
  }),
);

/** Well search: API number, well name/lease, or operator (rrc.wells). */
gisRouter.get(
  "/wells/search",
  asyncHandler(async (req, res) => {
    const { q } = searchSchema.parse(req.query);
    const rows = await prisma.$queryRawUnsafe<
      { fid: number; api8: string | null; wellNo: string | null; leaseName: string | null; operator: string | null; type: string | null; county: string; lon: number; lat: number }[]
    >(
      `SELECT fid, api8, well_no AS "wellNo", lease_name AS "leaseName", operator, type, county,
              ST_X(geom) AS lon, ST_Y(geom) AS lat
         FROM rrc.wells
        WHERE api8 LIKE '%' || $1 || '%' OR api10 LIKE '%' || $1 || '%'
           OR lease_name ILIKE '%' || $1 || '%' OR operator ILIKE '%' || $1 || '%'
           OR well_no = upper($1)
        ORDER BY county, lease_name NULLS LAST
        LIMIT 100`,
      q,
    );
    res.json(rows);
  }),
);

/** Full well detail for the map panel, including permits and completions. */
gisRouter.get(
  "/wells/:fid",
  asyncHandler(async (req, res) => {
    const fid = Number(req.params.fid);
    if (!Number.isInteger(fid)) return res.status(400).json({ error: "invalid fid" });
    const rows = await prisma.$queryRawUnsafe<Record<string, unknown>[]>(
      `SELECT fid, api8, api10 AS api, well_no AS "wellNo", well_id AS "wellId", symbol, type, status,
              county, district, lease_no AS "leaseNo", lease_name AS "leaseName",
              operator, operator_no AS "operatorNo", field_no AS "fieldNo", field_name AS field,
              oil_gas AS "oilGas", formations, spud_date AS "spudDate", plug_date AS "plugDate",
              cum_oil AS "cumOil", cum_gas AS "cumGas", last_prod AS "lastProd",
              replace(abstract, '?', '') AS abstract, survey, abstract_id AS "abstractId",
              ST_X(geom) AS lon, ST_Y(geom) AS lat
         FROM rrc.wells WHERE fid = $1`,
      fid,
    );
    if (!rows.length) return res.status(404).json({ error: "well not found" });
    const well = rows[0];
    const [permits, completions] = await Promise.all([
      prisma.$queryRawUnsafe<Record<string, unknown>[]>(
        `SELECT status_no AS "statusNo", permit_date AS "permitDate", operator, lease_name AS "leaseName", well_no AS "wellNo"
           FROM rrc.permits WHERE api8 = $1 ORDER BY permit_date DESC NULLS LAST LIMIT 12`,
        String(well.api8 ?? "")),
      prisma.$queryRawUnsafe<Record<string, unknown>[]>(
        `SELECT tracking_no AS "trackingNo", filing_type AS "filingType", status,
                filed_date AS "filedDate", completion_date AS "completionDate", field_name AS "fieldName"
           FROM rrc.completions WHERE api8 = $1 ORDER BY filed_date DESC NULLS LAST LIMIT 12`,
        String(well.api8 ?? "")),
    ]);
    res.json({ ...well, permits, completions });
  }),
);

// Bound the raw string so a pathological county list can't build a giant
// ANY($1::text[]) array; the names are sliced again below as defense in depth.
const optionsSchema = z.object({ counties: z.string().max(4000).optional() });

/**
 * Survey/abstract filter option lists, optionally scoped to counties
 * (comma-separated names). Replaces the client building these from
 * downloaded GeoJSON.
 */
gisRouter.get(
  "/options",
  asyncHandler(async (req, res) => {
    const { counties } = optionsSchema.parse(req.query);
    const names = (counties ?? "").split(",").map((s) => s.trim()).filter(Boolean).slice(0, 500);
    // county = ANY('{}') matches nothing, so an empty list means "all counties".
    const scope = names.length ? `county = ANY($1::text[]) AND` : "";
    const params = names.length ? [names] : [];
    const surveys = await prisma.$queryRawUnsafe<{ v: string }[]>(
      `SELECT DISTINCT survey AS v FROM gis.abstracts WHERE ${scope} survey IS NOT NULL ORDER BY v`,
      ...params,
    );
    const abstracts = await prisma.$queryRawUnsafe<{ v: string }[]>(
      `SELECT DISTINCT replace(abstract, '?', '') AS v FROM gis.abstracts WHERE ${scope} abstract IS NOT NULL ORDER BY v`,
      ...params,
    );
    // Well-derived filter option lists from rrc.wells, same county scoping.
    const wScope = names.length ? `WHERE county = ANY($1::text[])` : "";
    const wellAgg = await prisma.$queryRawUnsafe<{ types: string[]; statuses: string[]; operators: string[]; n: number }[]>(
      `SELECT array_agg(DISTINCT type) FILTER (WHERE type IS NOT NULL) AS types,
              array_agg(DISTINCT status) FILTER (WHERE status IS NOT NULL) AS statuses,
              array_agg(DISTINCT operator) FILTER (WHERE operator IS NOT NULL) AS operators,
              count(*)::int AS n
         FROM rrc.wells ${wScope}`,
      ...params,
    );
    const w = wellAgg[0];
    res.json({
      surveys: surveys.map((r) => r.v),
      abstracts: abstracts.map((r) => r.v).sort((a, b) => a.localeCompare(b, undefined, { numeric: true })),
      wellTypes: (w?.types ?? []).sort(),
      wellStatuses: (w?.statuses ?? []).sort(),
      operators: (w?.operators ?? []).sort(),
      wellCount: w?.n ?? 0,
    });
  }),
);

/**
 * Bounding box of everything matching the current map filters — powers the
 * map's "zoom to filtered results" behavior. Filter values arrive as repeated
 * query params (?operators=A&operators=B) because operator names can contain
 * commas. Precedence: any well-level filter (type/status/operator) frames the
 * matching wells; otherwise abstract/survey filters frame matching abstracts;
 * otherwise the selected counties frame themselves.
 */
/**
 * Pure query planner for /extent (exported for tests): picks the table whose
 * extent best represents "the filtered results" and builds the parameterized
 * predicate list. Returns null when no filter is set.
 */
export function planExtentQuery(q: Record<string, unknown>): { sql: string; params: string[][] } | null {
  const list = (k: string): string[] =>
    (Array.isArray(q[k]) ? (q[k] as unknown[]) : q[k] == null ? [] : [q[k]])
      .map((s) => String(s).trim()).filter(Boolean).slice(0, 500);
  const counties = list("counties"), surveys = list("surveys"), abstracts = list("abstracts");
  const wellTypes = list("wellTypes"), wellStatuses = list("wellStatuses"), operators = list("operators");

  const params: string[][] = [];
  const cond = (col: string, vals: string[]): string => { params.push(vals); return `${col} = ANY($${params.length}::text[])`; };

  if (wellTypes.length || wellStatuses.length || operators.length) {
    const conds: string[] = [];
    if (counties.length) conds.push(cond("county", counties));
    if (surveys.length) conds.push(cond("survey", surveys));
    if (abstracts.length) conds.push(cond("replace(abstract, '?', '')", abstracts));
    if (wellTypes.length) conds.push(cond("type", wellTypes));
    if (wellStatuses.length) conds.push(cond("status", wellStatuses));
    if (operators.length) conds.push(cond("operator", operators));
    return { sql: `SELECT ST_Extent(geom)::text AS ext FROM rrc.wells WHERE ${conds.join(" AND ")}`, params };
  }
  if (surveys.length || abstracts.length) {
    const conds: string[] = [];
    if (counties.length) conds.push(cond("county", counties));
    if (surveys.length) conds.push(cond("survey", surveys));
    if (abstracts.length) conds.push(cond("replace(abstract, '?', '')", abstracts));
    return { sql: `SELECT ST_Extent(geom)::text AS ext FROM gis.abstracts WHERE ${conds.join(" AND ")}`, params };
  }
  if (counties.length) {
    return { sql: `SELECT ST_Extent(geom)::text AS ext FROM gis.counties WHERE ${cond("name", counties)}`, params };
  }
  return null;
}

gisRouter.get(
  "/extent",
  asyncHandler(async (req, res) => {
    const plan = planExtentQuery(req.query as Record<string, unknown>);
    if (!plan) return res.json({ bbox: null });
    const rows = await prisma.$queryRawUnsafe<{ ext: string | null }[]>(plan.sql, ...plan.params);
    res.json({ bbox: parseExtent(rows[0]?.ext ?? null) });
  }),
);

/**
 * Flat abstract index for the deal abstract picker (id → label mapping).
 * ~11k rows at 12 counties — fine for a one-shot cached fetch; this becomes a
 * proper search endpoint before the statewide import lands.
 */
gisRouter.get(
  "/abstracts-index",
  asyncHandler(async (_req, res) => {
    const rows = await prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; countyFips: string }[]>(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, county_fips AS "countyFips" FROM gis.abstracts ORDER BY county, abstract`,
    );
    // Shared, org-independent reference geometry — safe to cache so this full
    // ~11k-row fetch isn't repeated on every map load.
    res.setHeader("Cache-Control", "public, max-age=3600");
    res.json(rows);
  }),
);

/** Full geometry for a small set of abstracts (deal footprint rendering). */
gisRouter.get(
  "/features",
  asyncHandler(async (req, res) => {
    const ids = String(req.query.ids ?? "").split(",").map((s) => s.trim()).filter(Boolean).slice(0, 500);
    if (!ids.length) return res.json({ type: "FeatureCollection", features: [] });
    const rows = await prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; area: number | null; geom: string }[]>(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county, area_m2 AS area, ST_AsGeoJSON(geom, 6) AS geom
         FROM gis.abstracts WHERE id = ANY($1::text[])`,
      ids,
    );
    res.json({
      type: "FeatureCollection",
      features: rows.map((r) => ({
        type: "Feature",
        properties: { id: r.id, abstract: r.abstract, survey: r.survey, county: r.county, area: r.area },
        geometry: JSON.parse(r.geom) as unknown,
      })),
    });
  }),
);

/**
 * Lease-level monthly production for a county (B5: rrc.production, from the
 * PDQ dump). Response matches the shape of the old static
 * /data/{county}-production.json assets so the heat-map pipeline and the
 * well-panel chart consume it unchanged:
 *   { "OG|district|leaseNo": [[yyyymm, oil_bbl, gas_mcf], ...], ... }
 * Oil includes condensate; gas includes casinghead. Months with no reported
 * volume are simply absent (zeros are dropped at import).
 */
const productionSchema = z.object({
  county: z.string().trim().min(1).max(40),
  months: z.coerce.number().int().min(1).max(1200).default(120),
});
gisRouter.get(
  "/production",
  asyncHandler(async (req, res) => {
    const { county, months } = productionSchema.parse(req.query);
    // Anchor the window to the latest reported month, not the calendar —
    // RRC production lags 2–4 months.
    const latest = await prisma.$queryRawUnsafe<{ mx: number | null }[]>(
      `SELECT max(cycle_ym)::int AS mx FROM rrc.production WHERE county = $1`, county);
    const mx = latest[0]?.mx;
    if (!mx) return res.json({});
    const y = Math.floor(mx / 100), m = mx % 100;
    const total = y * 12 + (m - 1) - (months - 1);
    const from = Math.floor(total / 12) * 100 + (total % 12) + 1;
    const rows = await prisma.$queryRawUnsafe<
      { key: string; ym: number; oil: number; gas: number }[]
    >(
      `SELECT og_code || '|' || district || '|' || lease_no AS key, cycle_ym AS ym,
              sum(oil_bbl + cond_bbl)::int AS oil, sum(gas_mcf + csgd_mcf)::int AS gas
         FROM rrc.production
        WHERE county = $1 AND cycle_ym >= $2
        GROUP BY 1, 2 ORDER BY 1, 2`,
      county, from,
    );
    const out: Record<string, [number, number, number][]> = {};
    for (const r of rows) (out[r.key] ??= []).push([r.ym, r.oil, r.gas]);
    res.setHeader("Cache-Control", "private, max-age=3600");
    res.json(out);
  }),
);

/** Bounding box + feature detail for one abstract (used to frame selections). */
gisRouter.get(
  "/abstracts/:id",
  asyncHandler(async (req, res) => {
    const rows = await prisma.$queryRawUnsafe<
      { id: string; abstract: string | null; survey: string | null; county: string; minx: number; miny: number; maxx: number; maxy: number }[]
    >(
      `SELECT id, replace(abstract, '?', '') AS abstract, survey, county,
              ST_XMin(geom) AS minx, ST_YMin(geom) AS miny, ST_XMax(geom) AS maxx, ST_YMax(geom) AS maxy
         FROM gis.abstracts WHERE id = $1`,
      String(req.params.id),
    );
    if (!rows.length) return res.status(404).json({ error: "abstract not found" });
    res.json(rows[0]);
  }),
);
