import { Router } from "express";
import { z } from "zod";
import { prisma } from "../db.js";
import { asyncHandler } from "../middleware/errors.js";
import { requireAuth, requireOrg, requirePermission } from "../middleware/auth.js";

/**
 * GIS Phase A (see docs/architecture/0003-gis-scale-architecture.md).
 *
 * Cadastral data lives in PostGIS (`gis` schema on the existing Neon DB) and is
 * delivered to MapLibre as vector tiles generated by ST_AsMVT. Search and
 * filter-option lists are trigram-backed queries — the client no longer needs
 * any abstract data downloaded to search or filter it.
 *
 * Tiles are mounted un-authed: MapLibre tile requests don't carry the
 * Authorization header, and the payload is public-record survey geometry
 * (same data UT BEG serves publicly). Everything org- or deal-related stays
 * on the authed routers.
 */

const TILE_EXTENT = 4096;
const TILE_BUFFER = 64;
/** Below this zoom a tile would span several counties' worth of polygons. */
const TILE_MIN_ZOOM = 6;
const TILE_MAX_ZOOM = 22;

// Tiny insertion-order LRU. Cadastral data changes only on re-import, so a
// process-lifetime cache is safe; Railway redeploys (and imports precede
// deploys) naturally flush it.
const tileCache = new Map<string, Buffer>();
const TILE_CACHE_MAX = 500;
function cachePut(key: string, buf: Buffer): void {
  if (tileCache.size >= TILE_CACHE_MAX) {
    const oldest = tileCache.keys().next().value;
    if (oldest !== undefined) tileCache.delete(oldest);
  }
  tileCache.set(key, buf);
}

export const gisTilesRouter = Router();

gisTilesRouter.get(
  "/:z/:x/:y.pbf",
  asyncHandler(async (req, res) => {
    const z = Number(req.params.z), x = Number(req.params.x), y = Number(req.params.y);
    if (!Number.isInteger(z) || !Number.isInteger(x) || !Number.isInteger(y) || z < 0 || z > TILE_MAX_ZOOM || x < 0 || y < 0 || x >= 2 ** z || y >= 2 ** z) {
      return res.status(400).json({ error: "invalid tile coordinates" });
    }
    res.setHeader("Content-Type", "application/x-protobuf");
    res.setHeader("Cache-Control", "public, max-age=3600");
    if (z < TILE_MIN_ZOOM) return res.status(204).end();

    const key = `${z}/${x}/${y}`;
    const hit = tileCache.get(key);
    if (hit) return res.send(hit);

    // Bbox filter runs against the 4326 GIST index; only intersecting rows get
    // transformed/clipped. ST_AsMVTGeom quantizes to the tile grid, so payload
    // size tracks the viewport, not the table.
    const rows = await prisma.$queryRawUnsafe<{ tile: Buffer | null }[]>(
      `WITH bounds AS (SELECT ST_TileEnvelope($1::int, $2::int, $3::int) AS env),
       mvtgeom AS (
         SELECT ST_AsMVTGeom(ST_Transform(a.geom, 3857), bounds.env, ${TILE_EXTENT}, ${TILE_BUFFER}, true) AS geom,
                a.id, a.county, a.abstract, a.survey, a.area_m2 AS area
           FROM gis.abstracts a, bounds
          WHERE a.geom && ST_Transform(ST_Expand(bounds.env, 4000), 4326)
       )
       SELECT ST_AsMVT(mvtgeom, 'abstracts', ${TILE_EXTENT}, 'geom') AS tile
         FROM mvtgeom WHERE geom IS NOT NULL`,
      z, x, y,
    );
    const tile = rows[0]?.tile;
    if (!tile || tile.length === 0) return res.status(204).end();
    cachePut(key, tile);
    res.send(tile);
  }),
);

export const gisRouter = Router();
gisRouter.use(requireAuth, requireOrg, requirePermission("viewMap"));

const searchSchema = z.object({ q: z.string().trim().min(1).max(120) });

/** Abstract/survey search across every imported county (trigram-indexed). */
gisRouter.get(
  "/search",
  asyncHandler(async (req, res) => {
    const { q } = searchSchema.parse(req.query);
    const rows = await prisma.$queryRawUnsafe<
      { id: string; abstract: string | null; survey: string | null; county: string; lon: number; lat: number }[]
    >(
      `SELECT id, abstract, survey, county,
              ST_X(ST_PointOnSurface(geom)) AS lon, ST_Y(ST_PointOnSurface(geom)) AS lat
         FROM gis.abstracts
        WHERE abstract ILIKE '%' || $1 || '%' OR survey ILIKE '%' || $1 || '%'
        ORDER BY GREATEST(similarity(coalesce(abstract, ''), $1), similarity(coalesce(survey, ''), $1)) DESC,
                 county, abstract
        LIMIT 20`,
      q,
    );
    res.json(rows);
  }),
);

const optionsSchema = z.object({ counties: z.string().optional() });

/**
 * Survey/abstract filter option lists, optionally scoped to counties
 * (comma-separated names). Replaces the client building these from
 * downloaded GeoJSON.
 */
gisRouter.get(
  "/options",
  asyncHandler(async (req, res) => {
    const { counties } = optionsSchema.parse(req.query);
    const names = (counties ?? "").split(",").map((s) => s.trim()).filter(Boolean);
    // county = ANY('{}') matches nothing, so an empty list means "all counties".
    const scope = names.length ? `county = ANY($1::text[]) AND` : "";
    const params = names.length ? [names] : [];
    const surveys = await prisma.$queryRawUnsafe<{ v: string }[]>(
      `SELECT DISTINCT survey AS v FROM gis.abstracts WHERE ${scope} survey IS NOT NULL ORDER BY v`,
      ...params,
    );
    const abstracts = await prisma.$queryRawUnsafe<{ v: string }[]>(
      `SELECT DISTINCT abstract AS v FROM gis.abstracts WHERE ${scope} abstract IS NOT NULL ORDER BY v`,
      ...params,
    );
    res.json({
      surveys: surveys.map((r) => r.v),
      abstracts: abstracts.map((r) => r.v).sort((a, b) => a.localeCompare(b, undefined, { numeric: true })),
    });
  }),
);

/**
 * Flat abstract index for the deal abstract picker (id → label mapping).
 * ~11k rows at 12 counties — fine for a one-shot cached fetch; this becomes a
 * proper search endpoint before the statewide import lands.
 */
gisRouter.get(
  "/abstracts-index",
  asyncHandler(async (_req, res) => {
    const rows = await prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; countyFips: string }[]>(
      `SELECT id, abstract, survey, county, county_fips AS "countyFips" FROM gis.abstracts ORDER BY county, abstract`,
    );
    res.json(rows);
  }),
);

/** Full geometry for a small set of abstracts (deal footprint rendering). */
gisRouter.get(
  "/features",
  asyncHandler(async (req, res) => {
    const ids = String(req.query.ids ?? "").split(",").map((s) => s.trim()).filter(Boolean).slice(0, 500);
    if (!ids.length) return res.json({ type: "FeatureCollection", features: [] });
    const rows = await prisma.$queryRawUnsafe<{ id: string; abstract: string | null; survey: string | null; county: string; area: number | null; geom: string }[]>(
      `SELECT id, abstract, survey, county, area_m2 AS area, ST_AsGeoJSON(geom, 6) AS geom
         FROM gis.abstracts WHERE id = ANY($1::text[])`,
      ids,
    );
    res.json({
      type: "FeatureCollection",
      features: rows.map((r) => ({
        type: "Feature",
        properties: { id: r.id, abstract: r.abstract, survey: r.survey, county: r.county, area: r.area },
        geometry: JSON.parse(r.geom) as unknown,
      })),
    });
  }),
);

/** Bounding box + feature detail for one abstract (used to frame selections). */
gisRouter.get(
  "/abstracts/:id",
  asyncHandler(async (req, res) => {
    const rows = await prisma.$queryRawUnsafe<
      { id: string; abstract: string | null; survey: string | null; county: string; minx: number; miny: number; maxx: number; maxy: number }[]
    >(
      `SELECT id, abstract, survey, county,
              ST_XMin(geom) AS minx, ST_YMin(geom) AS miny, ST_XMax(geom) AS maxx, ST_YMax(geom) AS maxy
         FROM gis.abstracts WHERE id = $1`,
      String(req.params.id),
    );
    if (!rows.length) return res.status(404).json({ error: "abstract not found" });
    res.json(rows[0]);
  }),
);
